### ISSUE TITLE
Character isn't moving

### ISSUE THREAD

**Issue by NeXzRo** [ffxivcode/AutoDuty#1]
so i got all the required plugin's and the path's but my character isn't moving are there any instructions?

**Comment by adambennett55** [comment]
can you post of a screen shot of the logs and exact steps you took after opening the plugin so i may repro

**Comment by adambennett55** [comment]
hmm 

18:00:41.377 | ERR | [vnavmesh] Failed to find a path from <359,5259. 45,881603. -225,4176> (1000000300019) to <34775850. 44145948. -22321496> (0): failed to find polygon on a mesh


these numbers dont look right

its like its swaping , and .

**Comment by adambennett55** [comment]
i see its a culture thing, v34 should fix this.
