### ISSUE TITLE
Boss mod AI max distance to target reset every duty pop

### ISSUE THREAD

**Issue by yudistiraen** [ffxivcode/AutoDuty#101]
i have this issue from recent update that caused boss mod AI `max distance to target` and `follow target slot` will reset every duty pop, dats kinda annoying that i need to adjust it again

related issue : 
https://github.com/awgil/ffxiv_bossmod/issues/398

**Comment by adambennett55** [comment]
Goto Config Tab and unchecked Manage BossMod AI Settings.

**Comment by yudistiraen** [comment]
oow, i thought that's an issue, thankyou
