### ISSUE TITLE
[Request] Option to automatically log out or kill game

### ISSUE THREAD

**Issue by eellllee** [ffxivcode/AutoDuty#12]
I'm not sure how difficult this would be to implement, but it'd be great to have the option to have the game automatically log out or kill the game when X amount of repetitions are done. Or the option to automatically leave the duty and stop the plugin itself if there hasn't been any combat in X amount of minutes, to avoid having the character run into a wall for too long - an issue I found happens often in dungeons that have area changes.

**Comment by adambennett55** [comment]
AutoKillClient and AutoLogout has been implemented, The other option will be explored when the anti stuck system is implemented
