### ISSUE TITLE
can't run unsync dungeons

### ISSUE THREAD

**Issue by K0shachiyamyatA** [ffxivcode/AutoDuty#124]
stuck on duty finder
![ffxiv_dx11_KVzMRujukw](https://github.com/user-attachments/assets/35b61ae0-6dd1-4a91-bcbf-28032e6a7c95)

**Comment by adambennett55** [comment]
is this 100% repro? can you show me all your settings so i can try

**Comment by adambennett55** [comment]
I will investigate this!
