### ISSUE TITLE
tank alexandria path gets stuck

### ISSUE THREAD

**Issue by Ocean1148** [ffxivcode/AutoDuty#129]
The first wtw pack after boss 1 where you go up the stairs and the robo birds spawn. As a tank you just keep running into the corner and eventually die cause it messes with the trust/support healer ai and you stop getting healed / get 1shot by multiple of the bird aoe cleaves at once. After dying there the path bugs out and you indefinitely run into a wall (the exit instance wall)

fix to it would just to be to end that wtw path before the staircase since the birds spawn at that point before going up the stairs.

**Comment by adambennett55** [comment]
I will defer this to Vera who wrote those paths

**Comment by Enthusiastus** [comment]
I fixed this problem here https://github.com/ffxivcode/AutoDuty/pull/134 the waypoint was a bit off, the character will now wait for combat and then climb the stairs.
