### ISSUE TITLE
Auto Desynthesis is not working

### ISSUE THREAD

**Issue by steamPUNK70** [ffxivcode/AutoDuty#13]
The setting is grayed out, I can't interact with it in any way. All settings work except this one. I thought the problem might be conflicting plugins, so I disabled any that might be interfering. It still doesn't help. 
![zJYExUHYUkc](https://github.com/ffxivcode/AutoDuty/assets/168932883/b6eccd60-14e6-4e5d-8a5e-41763cb6f692)

**Comment by adambennett55** [comment]
This has not been implemented yet, thats why its greyed out, its coming
