### ISSUE TITLE
V&C Dungeon - Mount Rokkon 

### ISSUE THREAD

**Issue by rafaelfneves** [ffxivcode/AutoDuty#130]
Is there a possibility to make a path for Mount Rokkon and others criteria's dungeons or not? I'm trying with a friend of mine to build a path but we can't for some reason... Just out of curiosity, thanks a lot!

**Comment by adambennett55** [comment]
I do not have Variants unlocked, I will defer this question to Vera.

**Comment by VeraNala** [comment]
I'm currently putting together Paths for Mount Rokkon, but they are quite complex and not yet fully supported in AD, RSR, or BMR.
I'll be working on the AD side of things and opening appropriate issues in RSR/BMR in the near future to address these dungeons.
So hopefully soon!

**Comment by adambennett55** [comment]
I remember you adding VariantManager and MountRokkon paths, can this be marked as completed?

**Comment by VeraNala** [comment]
As far as AD is concerned, yes, all routes are complete with the exception of # 12 which will likely require tweaks after RSR adjustments are made.

But for full automation, the paths will still require various updates from RSR:
- to support the use of variant actions like cure, 
- and some special logic in route 12 involving selective targeting)

As well as BMR:
- various path bosses/variations are missing crucial mechanics in their modules, which when combined with the inability to use variant cure, leads to wipes in autoduty.

**Comment by adambennett55** [comment]
Perfect thx
