### ISSUE TITLE
[Request] Better overlay

### ISSUE THREAD

**Issue by Avadonia** [ffxivcode/AutoDuty#131]
New overlay is super usefull but is slightly annoying to use a command to toggle it on/off would be great, as of now you need to tick "show overlay" off and on again if you closed it. 
Some settings to alter it's appearance would be great as it can stick out quite a bit right now, perhaps a "prevent moving" with a background removal.

**Comment by Avadonia** [comment]
You should probably either add the command in the command list on the plugin description, or also add button for background/lock on the config menu so that people know about this ^

**Comment by Avadonia** [comment]
Also since this kind of fall into "better overlay" the go to barrack sometime doesn't get close enough and do not select the door and loop the "going to" and "retrying something" making a step in front enter the barrack with no issue

**Comment by adambennett55** [comment]
which City

**Comment by Avadonia** [comment]
Ah sorry forgot there was different city, it's gridania

**Comment by adambennett55** [comment]
ok i will check it out
