### ISSUE TITLE
Choose trust partners

### ISSUE THREAD

**Issue by thechocorooms** [ffxivcode/AutoDuty#133]
Would there be a way to choose specific trust partners - when looping dungeons for leveling it only chooses the first three in the list, and I wanted to use this to help with leveling all my trust partners

**Comment by erdelf** [comment]
queue manually with what you want, exit. Then use AutoDuty. it remembers.

**Comment by thechocorooms** [comment]
Oh, I was missing a step. Thank you and sorry for the bother!
