### ISSUE TITLE
[Feature Request] Customisable timer between dungeons or full AutoRetainer integration.

### ISSUE THREAD

**Issue by Rakmarok** [ffxivcode/AutoDuty#144]
Hello!

I would like to request a feature that makes Retainers more convenient and feasible during looped dungeon runs.

One would be a customisable timer that starts when outside of a dungeon that waits the set time before continuing AD operation (like desynth, repair or queueing for a new dungeon).

The other would be full AutoRetainer implementation, meaning:

- Retainer finishes during dungeon: AD finished the current dungeon and upon exist suspends all operation until AR gives the all clear.
- Retainers are finished within "X amount of time" (set by the user) either when starting AD or when coming out of a dungeon: AD waits for retainers to be finished, suspends all operation and continues when AR gives the all clear.

Thank you. AD is a truly amazing tool.

**Comment by adambennett55** [comment]
First request implemented in #164, leaving open for 2nd request
