### ISSUE TITLE
[Request] Enable Autoduty path creation for variant dungeons

### ISSUE THREAD

**Issue by Flavescent** [ffxivcode/AutoDuty#15]
It is not currently possible to build paths for variant dungeons. The Build tab displays the following message when in a variant dungeon: "You must enter a dungeon to Build a Path".

I recommend enabling this feature for variant dungeons. With the aid of variant actions, these are soloable, and can be ground for tomestones and cosmetics.

**Comment by adambennett55** [comment]
this will have to wait until I have these unlocked or until someone PR's the fix
