### ISSUE TITLE
Pathfining isn't working the right way.

### ISSUE THREAD

**Issue by DevilsCreed** [ffxivcode/AutoDuty#151]
Hi there.

In some instances the pathfinden isn't working as intended. Sohm'Al for excemple - In the middle of the dungeon it resets and tries to run all the way back to the beginning. Some times it won't even start at all.

**Comment by adambennett55** [comment]
could you provide a Log in Debug mode when this happens please

**Comment by adambennett55** [comment]
I am going to close this issue until a response is made or this issue is confirmed
