### ISSUE TITLE
Usage documentation and error/logging in the addon

### ISSUE THREAD

**Issue by Heinzen** [ffxivcode/AutoDuty#157]
Currently the plugin will not run any DT dungeons in any of the characters I have (ones that are done with MSQ and fresh DT ones).

I currently have no idea why because some duties are enabled (non-greyed out) and some are disabled (greyed out). There are no tooltips, logs or information as to why I cannot queue to those. It does not seem to be character-specific either.

![image](https://github.com/user-attachments/assets/bb9ac48c-d50e-452f-aace-9273e90b35e9)

As a user, seeing a tooltip or other interface elements that would indicate why they are disabled (lack of mesh, job support, etc etc) would improve my experience.

Edit: been trying to look into this, so far I could not find it being related to a configuration issue or lack of another addon as my settings replicate the same settings of a friend's who works.

I have also double checked that the path files exist, although they do not show up in the Settings > Paths tab (but neither does for a friend whose plugin exists)
![image](https://github.com/user-attachments/assets/e3525756-0f96-4da7-883c-b952bb59bcf5)

**Comment by adambennett55** [comment]
There are only 2 reasons for Duties to be Greyed out, 1 - No Path file and 2 - Level is below the dungeon
Please click on the Paths tab and click open folder and ensure your paths are in that folder, if not please join us on discord for more troubleshooting

**Comment by Heinzen** [comment]
@adambennett55 how do I find the Discord server? Additionally, the issue was originally to point out that it would be great to have any sort of error handling with a tooltip or anything else that can point to the source of the error. I will keep troubleshooting to the Discord as I am still not able to use the plugin

**Comment by erdelf** [comment]
[Puni.sh discord](https://discord.gg/Zzrcc8kmvy). Join us in the autoduty channel.

**Comment by erdelf** [comment]
Fixed in discord, can close.
