### ISSUE TITLE
[Path] 1144 Doma Castle

### ISSUE THREAD

**Issue by Flavescent** [ffxivcode/AutoDuty#16]
I submit the following path for Doma Castle for inclusion in the plugin. I've tested it on repeat with a lv 67 ilv 270 WHM and it works. The character will eat several boss AOEs, but this is survivable with level-appropriate gear.

["MoveTo|297.25, 24.75, 57.42|","MoveTo|308.59, 25.05, -6.38|","MoveTo|203.70, 32.75, -17.67|","MoveTo|195.53, 36.75, 33.30|","Boss|126.05, 40.57, 17.44|","MoveTo|65.68, 40.00, 3.91|","MoveTo|14.77, 40.00, 123.26|","MoveTo|-25.23, 42.00, 86.06|","MoveTo|-66.32, 42.00, 125.34|","MoveTo|-109.06, 44.15, 106.72|","MoveTo|-148.55, 44.00, 110.31|","MoveTo|-189.95, 45.81, 123.85|","Boss|-233.89, 45.49, 130.58|","MoveTo|-240.75, 48.00, 25.44|","MoveTo|-208.28, 56.00, -38.75|","MoveTo|-240.22, 64.00, -85.45|","Boss|-239.86, 67, -196.72|"]

**Comment by adambennett55** [comment]
added
