### ISSUE TITLE
[Bug?] Path doesn't load properly after /xlrestart in dungeon

### ISSUE THREAD

**Issue by ladyredxiv** [ffxivcode/AutoDuty#174]
![image](https://github.com/user-attachments/assets/2d9c5e40-f738-43c6-8e86-137a5e13d6f5)

RSR bugged out and had a load error, so I used /xlrestart to quick reboot and.... well, that happened. ^
Backing out of the dungeon and going back in fixed it.

**Comment by erdelf** [comment]
temporary issue, if you just click start it loads the path.
