### ISSUE TITLE
[Feature] Force movement even if in combat

### ISSUE THREAD

**Issue by FFXIVRP-Developer** [ffxivcode/AutoDuty#18]
Trying to farm "The Wanderer's Palace" there is an un-targetable enemy that will continue attacking you until you are away from it. I'd like to know if there is a way for AutoDuty to not wait until combat is over and just continue moving so it can deal with the targetable threats somewhere else and continue its course.

I'd really appreciate this feature

**Comment by adambennett55** [comment]
I will add a action that can turn the stop for combat flag on and off
