### ISSUE TITLE
Auto duty swap while levelling

### ISSUE THREAD

**Issue by Alocie** [ffxivcode/AutoDuty#187]
Hi Team,

Can you add a option where the bot auto swaps to the next level available duty?

Currently it won't detect when the next level dungeon is available and auto swap which doesn't allow optimal XP levelling.

Thanks for your support.

**Comment by erdelf** [comment]
Just select the leveling option, it won't do every duty, as not every duty is all that stable, but it is specifically for that.

**Comment by leenakimoto** [comment]
> Just select the leveling option, it won't do every duty, as not every duty is all that stable, but it is specifically for that.

The stop looping @ Level option in Config?

**Comment by erdelf** [comment]
Not quite.
![image](https://github.com/user-attachments/assets/49bd126b-c55f-4b0d-9367-b93d8e55db59)

**Comment by leenakimoto** [comment]
Got it, thanks.
