### ISSUE TITLE
Alexandria Dungeon Bug

### ISSUE THREAD

**Issue by Alocie** [ffxivcode/AutoDuty#188]
Hi Team,

I noticed on the Alexandria Dungeon if you die after the 2nd Boss the bot runs back to the 2nd Boss Arena then just leaves.

I also died to some mobs before the last boss and it sat AFK at the shortcut.

I have VOD's but they are to big to upload on github.

**Comment by adambennett55** [comment]
I will not be able to look into this until I have the dungeon unlocked, Maybe Vera could take a look.

**Comment by adambennett55** [comment]
This should be fixed in commit 8bf3f55, if it still exists we will reopen this
