### ISSUE TITLE
trust level don't update 

### ISSUE THREAD

**Issue by TheBananaIntheButt** [ffxivcode/AutoDuty#189]
trust level don't update have to restart game for it to update and be able to select higher level dungon

**Comment by adambennett55** [comment]
well you wouldnt have to restart the whole game just autoduty!

**Comment by adambennett55** [comment]
This is being worked on

**Comment by reinbardt** [comment]
you can just disable-enable the plugin to make it force update tho, no need to restart the game

**Comment by erdelf** [comment]
fixed in #203
