### ISSUE TITLE
Boss Pathing Issue

### ISSUE THREAD

**Issue by sjil** [ffxivcode/AutoDuty#190]
When doing The Skydeep Cenote, at the first raidwide of the first boss, the pathing will move the character outside of the boss arena and infinitely reset it. If it manages to get stuck inside, it fails to solve the boss mechanics causing death and reset.

**Comment by filipinopepper** [comment]
@sjil how did you fix this? Mine is still doing it

**Comment by sjil** [comment]
i made a mistake in reading the instructions, you need Bossmods OR Bossmodreborn, just get reborn. i had both xD
