### ISSUE TITLE
Leveling option prefers the tower of Zot over the tower of Babil when at level 83. 

### ISSUE THREAD

**Issue by Dedoooo** [ffxivcode/AutoDuty#192]
Is there a reason for this or is this a bug? for now I have it manually running Babil til I unlock the next one, will see if issue repeats.

**Comment by erdelf** [comment]
correct. Those two dungeons are causing problems often enough that they are not in the leveling options.

**Comment by adambennett55** [comment]
Until the dungeons are confirmed stable, I will close this issue, also have some ideas in my head for further customization possibilities will talk to erdelf about it
