### ISSUE TITLE
Align camera to movement action box auto on in navmesh

### ISSUE THREAD

**Issue by zackfair1991** [ffxivcode/AutoDuty#197]
Is there any option to not change it by auto duty?

**Comment by erdelf** [comment]
no, it is required for paths.

**Comment by adambennett55** [comment]
I will, talk with the team and see if we can just turn it on for the actions that require it then back off

**Comment by VeraNala** [comment]
Not without overhauling every path again and introducing new actions to enable and disable it.
The alignment happens during moveTo steps to ensure that the camera is facing the proper direction BEFORE the automoves happen, so they would have to encompass each jumppad, transition, drop, and other instance/use of those actions.

We PR'd the ability to enable/disable the aligncamera config in the first place just to avoid having to do things like this and user error, whatever plugin that users are using that requires it to be off is more than capable of doing the same. =\

**Comment by adambennett55** [comment]
Well, there ya have it ;P I'm gonna go ahead and close this as won't fix.
