### ISSUE TITLE
BLU challanges

### ISSUE THREAD

**Issue by Pilocas** [ffxivcode/AutoDuty#199]
Hi!
Can you please make it so It can be used for BLU challanges?
ty!
Best Regasrds

**Comment by adambennett55** [comment]
I have not played blu at all so not sure whats involved in these challenges

**Comment by Pilocas** [comment]
Hi,

Thank you for your quick reply.

Maybe the option already exists and i simply dunno how to use it. If that The case I'm sory for bothering you.

Blue Challanges are nasicallt an arena with a special boss/ mobs that you'lll need to defeat. most of these challanges are not that difficul and you can cheese them, but the last few challanges cant be cheesed.

In comparison it would be more or less like the World bosses from fates, you also get a boss mod/bossmod reborn Window.

If you think its a possibility it would be much appreciated. 

If the possibility already exists and I simply dont understand how to use it, I would be much appreciated if you could explain it to me.

Best Regards

**Comment by VeraNala** [comment]
A few things:
At the moment RSR currently does not support Blue Mage rotations/skills, so unless another plugin does I don't see much point in adding this (at this time?) other than having a glorified Queuer for carnivale...
Also, I'm not entirely sure what your reason for wanting to *LOOP* carnivale stages would be...

Each week Carnivale selects 3 stages that it grants a bonus to - which grant some rewards, yes.
But you only have to clear them once, each, and usually while satisfying some (sometimes) complex conditions like using specific spell loadouts.
We *COULD* theoretically identify which stages are weekly targets and queue specifically for those, but again, as the conditions can change and the stages themselves also require various spell loadouts, they would have to be adjusted on a per-stage, per-challenge basis.

I feel like this is well outside of the scope of AD and would be better left to another plugin that specifically works around Blu or Carnivale.

**Comment by Pilocas** [comment]
ok, ty for you reply!
Best Regards
