### ISSUE TITLE
[Decommissioned?] Can't find the plugin anymore

### ISSUE THREAD

**Issue by FFXIVRP-Developer** [ffxivcode/AutoDuty#20]
Was the link to this plugin moved somewhere else? I enjoyed using this plugin and would love to continue using it if possible

**Comment by Flavescent** [comment]
The new repository is https://puni.sh/api/repository/herc. Add this to custom repositories in Dalamuud plugin installer settings under experimental.

**Comment by adambennett55** [comment]
yes sorry i updated the readme
