### ISSUE TITLE
Very recent update about "Loot Boss Treasure Only"

### ISSUE THREAD

**Issue by reinbardt** [ffxivcode/AutoDuty#201]
Apparently its just ignore boss chest and it just leave the dungeon

![Screenshot_2133](https://github.com/user-attachments/assets/41c43c4e-a753-4219-8aea-8d75bf2b4d2b)

**Comment by adambennett55** [comment]
what settings do you have set in AD for loot?

**Comment by reinbardt** [comment]
Default settings, and never actually tinker with any settings.
But now I gotta turn off the "Loot Boss Treasure Only" and now its working normally. The issue is just if people wants to have boss chest only I guess
![Screenshot_2140](https://github.com/user-attachments/assets/919f93a7-4e9f-4f0f-9637-54bd4ba6d7a9)
