### ISSUE TITLE
Kill Client/Logoff After Duty missing

### ISSUE THREAD

**Issue by InsecurePassword** [ffxivcode/AutoDuty#202]
The "Kill Client" and "Logoff After Duty" features appear to be missing in the new config settings.  In "Loop Termination Settings" there does appear to be a changeable option "On Completion of All Loops" but the only available option is "Do Nothing".

![image](https://github.com/user-attachments/assets/7a31cd3e-e610-4b93-ab40-38263dce7400)

**Comment by erdelf** [comment]
fixed in #204
