### ISSUE TITLE
AutoDuty not Looping after finished a dungeon

### ISSUE THREAD

**Issue by Rinmini** [ffxivcode/AutoDuty#205]
After updated the the new update not too long ago. Now it's not looping anymore, it would AFK after the dungeon is finished, no GC turning, no retainers, just re-food then AFK until the character got kicked out by anti-AFK system.
The overlay also disappears once dungeon is finished as well even with "Show Overlay" is on.
When Supports failed to kill the boss and everyone died, the overlay also disappears. 
![image](https://github.com/user-attachments/assets/216262bc-c8a2-4ec5-b0bc-70c57279df13)

**Comment by Rinmini** [comment]
I was running it as I wrote this issue, it's still not looping and the overlay still disappears, just now receiving your reply.

**Comment by erdelf** [comment]
You were running something that was not released? How exactly ?

**Comment by Rinmini** [comment]
I was running level 91 dungeon, but it would stop looping after that. Didn't have the issue before updating the new update today morning.

Reading issue #200 and tried that as well but still not looping. My friend has the previous update as he still haven't update the new one yet doesn't get this issue and he has both "recommended gears" on and no "delays" option yet on his version.

**Comment by Rinmini** [comment]
Working normally now, thank you!
