### ISSUE TITLE
Enhance AutoRetainer Integration behavior

### ISSUE THREAD

**Issue by BGFY91** [ffxivcode/AutoDuty#207]
Currently when retainers are available to be dispatched AD will always path the player to the inn to use the bell, even if they're standing directly in front of one. When choosing not to use the Retire To Inn functionality, this is a little unexpected.

It would be nice if AD would first check if there is a bell within interact range before choosing to path anywhere, and if there is to use that instead. To take it further, if there isn't a bell within range but there is a housing entrance nearby, perhaps it could act as AR's multimode does and enter before checking for a bell again?

It would have been nice if it were possible to simply request AR to use its find and use bell behavior from multimode but only for the currently in use character (rather than fully committing to using multimode).

**Comment by adambennett55** [comment]
If you are in the inn already will AR's find and use bell feature just use that bell?

**Comment by VeraNala** [comment]
Herc, there is an advanced feature in AR called Retainersense, that when left stationary for a long enough time next to a bell(10s by default, lower if needed), will automatically path you to it and interact with it.
It could remove the need for the Inn altogether assuming there is the IPC available to enable it.
(Here's a pic)
![ffxiv_dx11_U3rx4slC8O](https://github.com/user-attachments/assets/5ebc4e44-dfc3-4618-a4d2-911813107f6d)
