### ISSUE TITLE
[Path] 1065 The Aery

### ISSUE THREAD

**Issue by Flavescent** [ffxivcode/AutoDuty#21]
What follows is a path for The Aery that I've had success with looping using an appropriately geared AST. Because Bossmod doesn't support the fights yet, the player may die on occasion to boss mechanics, but in the majority of runs it works. There are a lot of gotos because vnavmesh seems to have navigation difficulties in some places.

["MoveTo|186.27, 60.94, 174.34|","MoveTo|259.34, 58.98, 131.90|","MoveTo|241.66, 64.96, 57.96|","MoveTo|304.08, 65.91, 22.43|","MoveTo|317.23, 70.47, -16.17|","MoveTo|300.48, 76.60, -63.65|","MoveTo|357.50, 80.94, -111.49|","MoveTo|369.42, 86.70, -147.33|","Boss|335.50, 94.00, -202.75|","MoveTo|313.35, 94.00, -177.20|","MoveTo|200.31, 10.72, -155.47|","MoveTo|228.93, -3.83, -55.05|","MoveTo|177.19, 1.13, -66.26|","MoveTo|182.26, 1.17, -79.02|","MoveTo|138.11, 5.87, -109.61|","MoveTo|116.74, 23.46, -30.08|","MoveTo|155.04, 37.62, 10.06|","MoveTo|50.52, 56.08, 63.46|","Boss|14.47, 60.00, 66.94|","MoveTo|-58.47, 82.01, 29.47|","MoveTo|-87.77, 93.08, -12.14|","MoveTo|-34.12, 108.28, -42.15|","MoveTo|10.12, 108.25, -28.72|","MoveTo|34.28, 108.07, -70.79|","MoveTo|76.85, 108.25, -29.69|","MoveTo|82.39, 107.70, -46.28|","MoveTo|100.80, 123.34, -90.10|","MoveTo|89.71, 123.27, -106.34|","MoveTo|34.86, 123.55, -87.75|","MoveTo|35.14, 130.09, -183.78|","Boss|35.49, 148.40, -262.59|"]

**Comment by adambennett55** [comment]
updated
