### ISSUE TITLE
[Bug] Repeating duties is broken

### ISSUE THREAD

**Issue by Flavescent** [ffxivcode/AutoDuty#22]
As of 0.0.0.44, whenever AutoDuty is set to more than 1 run, after the first run completes, AutoDuty starts the second run, then after the duty is loaded immediately quits out of the duty and does nothing. It must be manually stopped and restarted.

![image](https://github.com/ffxivcode/AutoDuty/assets/12690771/752a9ee0-b956-455c-9071-458f162f9da6)

**Comment by adambennett55** [comment]
I will look into this

**Comment by adambennett55** [comment]
I just ran a4n about 20 times looping with no issues, i am not able to repro this, does it happen everytime and is it just in SirenSong?

**Comment by Flavescent** [comment]
Thanks for looking into this. For me, the bug occurs when attempting to loop any dungeon (the ones I tried were Sirensong Sea, Doma Castle and Holminster Switch). Looping A4N, on the other hand, still works for me, as it does for you.

The bug only appeared after I changed repos from the old repo to the new repo, so any intervening changes might be the cause. What follows are my configs.

![image](https://github.com/ffxivcode/AutoDuty/assets/12690771/ca8ac64e-5bf6-458a-b87a-f4a601a29fc6)

**Comment by Flavescent** [comment]
As an update, it appears to depend on the dungeon in some way whether the bug occurs or not. For example, looping breaks in Tower of Zot, but not in Qitana Ravel or Mt. Gulg.

**Comment by hx0requiem** [comment]
Happened to me too with Sirensong Sea. Also, to include, running Sirensong Sea takes me to Sohr Kai for some reason and AutoDuty will only work for Sirensong if I start it inside the instance/dungeon itself.

**Comment by adambennett55** [comment]
Does this issue persist as of v57?

**Comment by Flavescent** [comment]
It's difficult to tell, as recent changes and game patches have variously enabled or disabled Autoduty features. But generally duty support looping in Dawntrail dungeons works well for me now. Thanks for your work!

**Comment by adambennett55** [comment]
great. if it starts happening again just reopen this issue
