### ISSUE TITLE
Running into wall on b3 room qitana ravel- path (823)

### ISSUE THREAD

**Issue by WubWubzz** [ffxivcode/AutoDuty#24]
After sliding down the log it tries to back track up to the log. coffers are on boss only.
![image_2024-05-24_124825572](https://github.com/ffxivcode/AutoDuty/assets/143079722/72009462-5353-433a-96bd-437781d0d1f8)
![Screenshot 2024-05-24 124602](https://github.com/ffxivcode/AutoDuty/assets/143079722/f04f0518-9c63-4bdd-a4b4-9b0696e65dbe)

**Comment by adambennett55** [comment]
is this still an issue?

**Comment by WubWubzz** [comment]
> is this still an issue?

No longer an issue no.
