### ISSUE TITLE
problem with Brayflox's Longstop Leveling Duty

### ISSUE THREAD

**Issue by HaruuTako** [ffxivcode/AutoDuty#245]
problem with Brayflox's Longstop Leveling Duty it stuck at Interactable Goblin Pathfinder need to stop and skip this to moveTo then run 

![image](https://github.com/user-attachments/assets/cae5efc7-4b82-4c93-920f-1661515e6dc0)

**Comment by HaruuTako** [comment]
![image](https://github.com/user-attachments/assets/fde66271-a777-44d8-a2c5-9c742403e1d1)

**Comment by HaruuTako** [comment]
how i can fix it ?

**Comment by adambennett55** [comment]
You can't it's an internal bug in AD and will be fixed soon
