### ISSUE TITLE
The Aitiascope - Going back and forth after teleporting after the 1st boss

### ISSUE THREAD

**Issue by leonelvin** [ffxivcode/AutoDuty#250]
This is a new issue that just starts to occur today (18/08) - yesterday it was fine until the new AutoDuty update.

The path that it is stuck with in the dungeon is:

Interactable|-5.86, 164.00, 471.21|2011758 (Aether Current)

After the 1st boss, we're supposed to interact with the Aether Current to move to the next section. Autoduty performs this correctly but when teleported to the new section, it doesn't jump to the next command. Instead, it's stuck here so the characters keep moving back and forth in a short range indefinitely.

**Comment by adambennett55** [comment]
please try again with v126

**Comment by leonelvin** [comment]
it's working again after the latest update. Thanks!
