### ISSUE TITLE
Skydeep Cenote - running off last boss platform

### ISSUE THREAD

**Issue by ayo-bruh** [ffxivcode/AutoDuty#252]
Char back to running off edge of B3 platform (away from boss) if path was paused at all, or wiped previously at B3 (like due to previous, or due to spread clipping/kb errors in BMR)

v126. AD at last boss step and will try to run off
Align camera to movement direction checked on in vnav
Legacy type movement. disable camera pivot checked on

**Comment by adambennett55** [comment]
please check this still exists in 131

**Comment by ayo-bruh** [comment]
appears to be solved in current release. and loops fine
