### ISSUE TITLE
Redundancy: Teleport for Retainers.

### ISSUE THREAD

**Issue by Wolfies11681** [ffxivcode/AutoDuty#262]
The current setup I have has my character after each dungeon:

- Go to House for retainers
- Go to Gridania for GC Turn ins.
- Start new Dungeon.

If I do more than one dungeon back to back, I end up teleporting from GC Turn in to my house for retainers. Then, back to Gridania to GC turn in.

I think you should add a check. If you are in Gridania near GC do turn in first. THEN, go to house and do retainers (if you designated house for retainers).

**Comment by adambennett55** [comment]
you could set your house as the retire to location and it will go back to your house everyloop

**Comment by adambennett55** [comment]
closing for now, since no reponse
