### ISSUE TITLE
Monitor Inventory for Better equipment loots

### ISSUE THREAD

**Issue by adambennett55** [ffxivcode/AutoDuty#268]
If found a better piece and its looted to your inventory, move to your armory so it can be caught with autoequiprecommended gear, during leveling, possibly even equip the gear immediately?

**Comment by MrGuffels** [comment]
![image](https://github.com/user-attachments/assets/405bc8f2-42c7-44d7-bdab-e23c8c92cf7c)
You might be able to cheat the feature by accessing this setting. Unless you were going to go all in and manage peoples Armory Chests to prevent the failstate caused by the Armory chest being full.

**Comment by erdelf** [comment]
no reason to do it like this. Already asked for IPC in gearsetter and got it

**Comment by adambennett55** [comment]
awesome. i will have to check it out i havent used it yet
