### ISSUE TITLE
`Help please

### ISSUE THREAD

**Issue by ImTerribleAtThisx** [ffxivcode/AutoDuty#3]
Hey, this isn't much of an issue, but as my name suggests, i'm new to this all, and im wondering, my path folder didn't have anything when I downloaded all the thingys, and only one of the paths which is the stone vigil, can I please have some help?
The dream would be to be able to do all of the duty roulettes automatically, or the squad ones atleast.
Niche would be all the ones for the HW relic (since ive already done 3 of them, the 11 dungeons is a hassle.

**Comment by adambennett55** [comment]
there will be a new release soon which will auto download the paths
