### ISSUE TITLE
Leveling mode causes crashes / hangs

### ISSUE THREAD

**Issue by ayo-bruh** [ffxivcode/AutoDuty#303]
since yesterday, i noticed leveling mode can occasionally cause crashes and hangs, like:
1) will try to queue for Holminster for leveling (when Qitana better option at 75), opens the vanilla menu then crashes. with generic Dalamud report

2) going from lv 96->97 (got level from Cenote), tries to queue for Vanguard, sits there on vanilla trust menu and doesnt queue. seemingly has to do with repair.
my chat log here:
“Reaper” registered.
Unable to execute command while occupied.
10 items repaired.

(previously i have only gotten crashes past approx 6mos from specific AD squadron issue, cause by trying to accept and requeue command mission with full inv, which is understandable tho. i'm not crashing a lot)

nothing in xllog from AD besides a generic message about B3 in Vanguard
full version of Dalamud, updated AD, maxed trust levels for all npcs and crafting, plenty of lv8dark matter. char has appropriate gear on for ilevel and such (aug. tome plus). no plugin options that might affect repair are enabled (ie Pandora) besides YesAlready. desynth, extract AD options off

**Comment by adambennett55** [comment]
please try with v135

**Comment by ayo-bruh** [comment]
> please try with v135

tested with 135. no crashes but some (maybe 1/5 of time) hanging again, with both leveling describe above, and non-leveling 91 dungeon q, so far

**Comment by ayo-bruh** [comment]
This continues to happen. Including in latest version, even just doing basic dungeon looping. Not sure why it was closed
