### ISSUE TITLE
Mutliboxing issue, no longer loads plugin. Duty selection stuck on single client sometimes?

### ISSUE THREAD

**Issue by Dedoooo** [ffxivcode/AutoDuty#310]
after the recent updates I'm no longer able to mutlibox as I used to before.
![image](https://github.com/user-attachments/assets/2ab21109-b9ea-44b8-9164-88a9b45869d0)
disabled and reenabled plugin after relaunching multiple times. issue is persisting with more than 1 client utilizing the plugin.

when on a single client, interaction suddenly stops at duty selection between loops and gets stuck at that. (happens inconsistently, I only have the recommended plugins set.)

**Comment by adambennett55** [comment]
try right clicking on autoduty and hit reset plugin

**Comment by adambennett55** [comment]
ok i will investigate
