### ISSUE TITLE
[Enhancement] Path Action that toggles RSR on/off

### ISSUE THREAD

**Issue by Katsuvera** [ffxivcode/AutoDuty#332]
Random thought I had while making W2W Paths:

Would it be possible to add a movement Action that stops your character from attacking enemies entirely? Something like a toggle akin to StopForCombat, but it toggles RSR on / off? I ask because I believe it would make DPS+Healer W2W Paths even more consistent.

Currently, depending on class and level, there are some classes that don't cast anything as they run by the first pack (some casters), some that attack just one enemy, and some that immediately use an AoE and attack all the enemies, thus making _some pack_ inconsistent on when and where the NPC Tank gets aggro on the enemies. I believe this addition would remedy that so that the Tank always gets aggro in the same spot, and you can then always bring the second pack back to the Tank in the same spot.

With that said, I believe my paths are decently consistent as is, so this isn't a high priority at all, I just figured I'd ask and see if maybe it's easily implemented. Thanks for your time.

**Comment by Katsuvera** [comment]
While I was lying in bed, I realized: Wait, can you do effectively this with the ChatCommand Action set to /rotation Off and /rotation Auto? So I got out of bed to test it.

To be clear, if I manually do /rotation Off myself during the run, it stays off just fine. (With one exception mentioned below.)

I'm finding that the /rotation Off step just causes RSR to flicker off briefly but it immediately gets turned back on. Also, of note, is that if I turn RSR off myself before that step, then it gets turned back on by that /rotation Off step... Which doesn't make any sense. lol So not sure what's going on with that.

The /rotation Auto step seems to work just fine, though.

**Comment by VeraNala** [comment]
Hi Katsu! I believe you are looking for these, which I used in one of the Mount Rokkon paths:

	"ChatCommand|0, 0, 0|/autoduty config AutoManageRSRState False",
	"ChatCommand|0, 0, 0|/rotation off",
	[Some Stuff]
	"ChatCommand|0, 0, 0|/autoduty config AutoManageRSRState True",
	"ChatCommand|0, 0, 0|/rotation auto",

**Comment by Herculezz55** [comment]
"ChatCommand|0, 0, 0|/autoduty config AutoManageRotationPluginState False", -- isnt necessary because i only Manage the state and start and end, so in a path it never gets set, 

"ChatCommand|0, 0, 0|/rotation off", -- this will only turn rsr off and on, there is a method in AutoDuty.cs that determines what rotation plugin is being used and turns on/off that plugin, might make sense to make an action that simply calls that method so rsr or autorot will be turnf off or on

**Comment by Herculezz55** [comment]
scratch that i forgot i had to add it back to incombat and boss steps cause everyones shit was turning off in rsr

**Comment by VeraNala** [comment]
Haha, well either way, yeah having some sort of disablecombat command might be nice for niche situations like this.
In Rokkon I believe I made use of this solely to get around it spamming sprint during some platforming parts
I'm not sure if I would make it a step though, as it might get confusing with stopforcombat, but maybe something internal?

**Comment by Herculezz55** [comment]
either we could add the action or add in the commands for autorot too, /vbm ar disable and /vbm ar set AutoDuty

**Comment by VeraNala** [comment]
Yes something that encompasses both is ideal

**Comment by Herculezz55** [comment]
Plugin.SetRotationPluginSettings(true) and Plugin.SetRotationPluginSettings(false) will determine which rotation plugin is being used and turn on or off said plugin
