### ISSUE TITLE
Category toggles don't work correctly

### ISSUE THREAD

**Issue by BGFY91** [ffxivcode/AutoDuty#335]
The `Enable` checkbox under each category is failing to work as intended.

Three different examples, one somewhat breaking,
1. If `Stop Looping @ Level` is enabled and set, but the Termination category is disabled, looping will still terminate as if the `Enable` checkbox does not exist.
2. If `Auto Equip Recommended Gear` and/or `Auto Consume` are checked, but the Pre-Loop category is disabled, they run anyway.
3. If `Enable AutoRetainer Integration` is enabled, but the Between Loop category is disabled, looping will hang between runs indefinitely. Presumably waiting for AR to do something, but it never does (nor does it attempt to locate the bell). Opening the config window and pressing `Stop` is the only fix (`Stop` button on the overlay is greyed out for some reason).

**Comment by VeraNala** [comment]
Adding that the Enable checkboxes underneath each config header are conflicting with one another - such that trying to disable one while another is visible will not allow for it - which might be causing these various other behaviour bugs
