### ISSUE TITLE
Loop gets stuck on trying to register for duty finder. Selects picked duty but never enters.

### ISSUE THREAD

**Issue by Dedoooo** [ffxivcode/AutoDuty#347]
When a loop is finished autoduty does all the steps to register again, however it never proceeds to enter the duty through duty finder as it is stuck on the selected duty, when manually qued, it proceeds with the loop.

**Comment by Herculezz55** [comment]
Can u post the log? And is it 100% repro, can u list exactly the scenario

**Comment by Herculezz55** [comment]
AutoRetainer being used by chance?

**Comment by Herculezz55** [comment]
This is not a bug this is intended, because other foods and pots and other stuff is alot more expensive, there are plans to expand this to do it during runs as well but we need to ensure out stuckhelper is more effective first
