### ISSUE TITLE
[Bug] AutoDuty not consuming food after the buff timer expires

### ISSUE THREAD

**Issue by ItzArchill** [ffxivcode/AutoDuty#350]
### What happened?

Whilst using AutoDuty, the "Auto Consume" option will only consume the food selected at the very first loop, but will not consume food after the buff expires. In an old version of AutoDuty when Boiled Eggs were the only option of food, it would refresh the food buff after each loop. Now it does not.
I will attach my AutoDuty settings
![image_2024-09-02_003428732](https://github.com/user-attachments/assets/f5e778aa-0385-47dd-8bc7-03b134b5e3b4)

### Version

Release

### Steps to reproduce the error

I have Auto Consume enabled with Boiled Egg selected (non-HQ) with the Boiled Egg added.
![image_2024-09-02_003154599](https://github.com/user-attachments/assets/fd948236-029e-4ed6-a38c-be62e9793447)

### Other relevant plugins installed

AutoDuty
BossMod Reborn
vnavmesh
Rotation Solver Reborn
Pandora's Box
YesAlready

**Comment by Herculezz55** [comment]
This is not a bug this is intended, because other foods and pots and other stuff is alot more expensive, there are plans to expand this to do it during runs as well but we need to ensure out stuckhelper is more effective first
