### ISSUE TITLE
[Feature Request] The Ability to Add "Comment" Steps

### ISSUE THREAD

**Issue by Katsuvera** [ffxivcode/AutoDuty#357]
### What problem are you trying to fix?

I've realized my Paths can get sorta convoluted and, if asked what step they're having issues with, the average person might not really be able to tell wtf is happening based on the path. For this reason, I believe being able to add "Comments" as Steps might help differentiate between parts of the path. Example image provided below.

### What is the solution to the problem?

Add Steps that are just used as "Comments", that don't actually do anything.

### Additional context

Once again, I'd say this _very low priority_, and not worth stressing over if it isn't feasible. The path can be parsed eventually, this would only help to make things easier for the average user... if they ever have any reason to try and figure out what the path is doing.

Here's a 'before' and an example 'after' image to provide additional context.
![image](https://github.com/user-attachments/assets/83916591-281c-4d1e-b776-304c92387ce3)
![image](https://github.com/user-attachments/assets/ee9e9ef3-2f1b-48b0-a453-185abf623d05)

**Comment by Herculezz55** [comment]
Comments are not supported in jsons, there are workarounds, but these require adding the comments as data pairs, this is certainly possible and trivial to implement, but to help make them easily noticed we would need to differentiate them from the rest of the actions, something like:
"_comment": "comment text"
Or
"//comment": "comment text"

Either way I can easily parse them out and add them to the display as green comment text and the path reader will skip them
