### ISSUE TITLE
[Feature Request] Add a treshold for consumption

### ISSUE THREAD

**Issue by RedactedFFXIV** [ffxivcode/AutoDuty#360]
### What problem are you trying to fix?

Currently it can happen often that while in dungeon the food runs out and the +3% exp is lost.

### What is the solution to the problem?

Add a threshold for food, which lets you set a value under which a new food is consumed

### Alternative solutions

Make it a fixed treshhold like 30minutes.

**Comment by Herculezz55** [comment]
There are plans for expanding the auto consume to also invoke in dungeon but thats low priority atm, i spose i could add a simple check box that says ignore status and it will consume whatever item every loop no matter if its already in your status
