### ISSUE TITLE
[Feature Request] New Leveling Mode

### ISSUE THREAD

**Issue by RedactedFFXIV** [ffxivcode/AutoDuty#367]
### What problem are you trying to fix?

That sometimes AutoDuty is in the same dungeon for 6 levels, which takes more time then it needs to.

### What is the solution to the problem?

Have a option for leveling mode, that will always select the next avaible dungeon.
So one with a path and with a module for bosses.

### Additional context

I currently do this manually, because I noticed that atleast at lvl 70 every job can do every dungeon without any problem.

**Comment by Aimsucks** [comment]
This is currently how Leveling Mode works. I'm not sure what feature you're trying to request.

**Comment by RedactedFFXIV** [comment]
It currently does not use lvl 77, lvl 79 etc. dungeons for lvling.
It uses specific dungeons like the lvl 75 or lvl 81.

**Comment by Kagekazu** [comment]
> It currently does not use lvl 77, lvl 79 etc. dungeons for lvling. It uses specific dungeons like the lvl 75 or lvl 81.

isnt this mostly since there are no boss modules for the other fights?

**Comment by RedactedFFXIV** [comment]
I did the lvl 77 & lvl 79 fights without any problems

**Comment by Aimsucks** [comment]
> So one with a path and with a module for bosses.

This is how the leveling route is selected. The leveling dungeons are vetted. I'm genuinely not sure what you're requesting.

**Comment by Katsuvera** [comment]
I hope it's not too presumptuous of me to add to this conversation but, to play devil's advocate for a moment: according to the spreadsheet, Mt. Gulg has a Module and does not have any notes saying it's inconsistent, which implies it could be added to Leveling Mode.

With that out of the way, like Aimsucks said in their recent message, Leveling Mode already does exactly what you suggested - it only includes dungeons with Paths and Modules that can _currently_ be consistently be cleared. As more modules get added to dungeons, and more dungeons become consistent, they will get added to Leveling mode - like how recently The Aery, The Vault, and Gubal Library were added to the HW levels. So eventually the idea is to have every dungeon included, it's just still a work in progress as modules are made for 'em.

**Comment by Aimsucks** [comment]
Couldn't agree more with @Katsuvera. I don't see why Mt. Gulg isn't added, but I think that's outside the scope of a vague feature request saying "why don't leveling dungeons use the highest level dungeon possible?"

This is the current list of leveling dungeons:
```cs
1037u, // TamTara Deepcroft
1039u, // The Thousand Maws of Toto-Rak
1041u, // Brayflox's Longstop
1042u, // Stone Vigil
1064u, // Sohm Al
1065u, // The Aery
1066u, // The Vault
1109u, // The Great Gubal Library
1142u, // Sirensong Sea
1144u, // Doma Castle
837u,  // Holminster
823u,  // Qitana
952u,  // Tower of Zot
974u,  // Ktisis Hyperboreia
```
This list is created with compatibility for VBM modules in mind. If you want more dungeons to be added, please read the module making guide [here](https://github.com/awgil/ffxiv_bossmod/wiki/Making-a-Module) and contribute modules for those dungeons.

**Comment by Herculezz55** [comment]
Leveling Mode already does what OP is asking for, and their is a process by which vera and erdelf determine what gets added, if and when a dungeon deems fit it will be added, with that being said I am going to close this.
