### ISSUE TITLE
[Bug]  non-support duties being run by command will crash the game

### ISSUE THREAD

**Issue by CacahuetesManu** [ffxivcode/AutoDuty#386]
### What happened?

"/autoduty run 151 1 true" and "/autoduty run 174 1 true" crashes the game

### Version Number

0.0.0.150

### Steps to reproduce the error

Type into in-game chat:

"/autoduty run 151 1 true"

**Comment by VeraNala** [comment]
Queuing for this while Trust was highlighted resulted in the following Log, did not enter the dungeon but navigation started:
********************************************
21:27:06.070 | DBG | [AutoDuty] Run: territoryType=151 loops=1 bareMode=True

21:27:06.070 | INF | [AutoDuty] Running AutoDuty in The World of Darkness, Looping 1 times in BareMode (No Pre, Between or Termination Loop Actions)

21:27:06.070 | DBG | [AutoDuty] Stage=Looping

21:27:06.078 | DBG | [AutoDuty] General Settings Active: Vnav_Align_Camera_Off, YesAlready

21:27:06.078 | DBG | [AutoDuty] Setting VnavAlignCamera: False

21:27:06.078 | DBG | [AutoDuty] Setting YesAlready Enabled: False

21:27:06.079 | INF | [AutoDuty] Running The World of Darkness 1 Times

21:27:06.094 | DBG | [AutoDuty] Starting to execute task: <Enqueue>b__0

21:27:06.107 | DBG | [AutoDuty] Queueing First Run

21:27:06.107 | DBG | [AutoDuty] Task <Enqueue>b__0 completed successfully

21:27:06.117 | DBG | [AutoDuty] Starting to execute task: Queue-Invoke

21:27:06.127 | INF | [AutoDuty] Queueing: Trust: The World of Darkness

21:27:06.127 | DBG | [AutoDuty] Task Queue-Invoke completed successfully

21:27:06.137 | DBG | [AutoDuty] Starting to execute task: EzThrottler.Throttle(Queue-Delay50, 50)

21:27:06.141 | DBG | [AutoDuty] Queue Helper - Opening Dawn

21:27:06.152 | DBG | [AutoDuty] Task EzThrottler.Throttle(Queue-Delay50, 50) completed successfully

21:27:06.161 | DBG | [AutoDuty] Starting to execute task: EzThrottler.Check(Queue-Delay50)

21:27:06.212 | DBG | [AutoDuty] Task EzThrottler.Check(Queue-Delay50) completed successfully

21:27:06.221 | DBG | [AutoDuty] Starting to execute task: Queue-WaitQueueComplete

21:27:06.405 | DBG | [AutoDuty] Queue Helper - You do not have expansion: 0 unlocked stopping

21:27:06.406 | INF | [AutoDuty] Done Queueing: Trust: The World of Darkness

21:27:06.415 | DBG | [AutoDuty] Task Queue-WaitQueueComplete completed successfully

21:27:06.429 | DBG | [AutoDuty] Starting to execute task: Queue-WaitNotValid

21:27:16.434 | VRB | [AutoDuty] Task Queue-WaitNotValid took too long to execute
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/Automation/LegacyTaskManager/TaskManager.cs:line 160

21:27:16.444 | DBG | [AutoDuty] Starting to execute task: Queue-WaitValid

21:27:16.456 | DBG | [AutoDuty] Task Queue-WaitValid completed successfully

21:27:16.467 | DBG | [AutoDuty] Starting to execute task: <Enqueue>b__0

21:27:16.476 | DBG | [AutoDuty] Done Queueing-WaitDutyStarted, NavIsReady

21:27:16.476 | DBG | [AutoDuty] Task <Enqueue>b__0 completed successfully

21:27:16.485 | DBG | [AutoDuty] Starting to execute task: Run-WaitDutyStarted

21:27:26.501 | VRB | [AutoDuty] Task Run-WaitDutyStarted took too long to execute
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/Automation/LegacyTaskManager/TaskManager.cs:line 160

21:27:26.510 | DBG | [AutoDuty] Starting to execute task: Run-WaitNavIsReady

21:27:26.520 | DBG | [AutoDuty] Task Run-WaitNavIsReady completed successfully

21:27:26.531 | DBG | [AutoDuty] Starting to execute task: <Enqueue>b__0

21:27:26.542 | DBG | [AutoDuty] Start Navigation

21:27:26.542 | DBG | [AutoDuty] Task <Enqueue>b__0 completed successfully

21:27:26.552 | DBG | [AutoDuty] Starting to execute task: Run-StartNavigation

21:27:26.564 | DBG | [AutoDuty] StartNavigation: startFromZero=True

21:27:26.564 | DBG | [AutoDuty] Task Run-StartNavigation completed successfully
*******************************************
It then also disabled the ability to interact with AutoDuty's UI -> 
![ffxiv_dx11_piuU1r4RGs](https://github.com/user-attachments/assets/58102d08-e8cd-459f-8da4-f7e72022aa74)


Resetting and trying it while the Correct Menu (Raid - Unsynced) was open/visible, queued up for the raid as expected.
