### ISSUE TITLE
[Bug] Keep running to wrong FC Estate plot even after setting Pre-Loop setting positions

### ISSUE THREAD

**Issue by GuyStructure** [ffxivcode/AutoDuty#388]
### What happened?

I haven't had this issue until a few days ago. My character keeps running to plot 29 Shirogane instead of plot 30 after teleporting to the estate. I asked in discord and was instructed to:

     1 - Goto Config, Pre-Loop Initialization Settings, Check Retire To, Select FC Estate in the Drop Down, goto your FC Estate, if the door is a straight shot from your tele loc, then just goto your door and hit Add Current Position, if not, Add Multiple positions that will get you to your door, by moving to each position and clicking Add Current Position.

I did as instructed and it worked the first time. When I teleport to Kugane and back to the FC estate my character ran into the correct house. But teleporting to Kugane again and back to the FC Estate to see if it still works. It does not. The Added positions are saved in the menu but the character ran back to plot 29.

The bug is after saving the location inputs it works the first time, but does not after the first time. The location path is saved. But the character still ran to plot 29 instead of plot 30.

Another bug is on the menu overlay bar, the "Goto" button when going to Apartment and FC Estate, the 'Stop' button is greyed out and cannot end command manually '/ad stop' or manually run to relevant location. 

### Version Number

v0.0.0.150

### Steps to reproduce the error

Please see what happened. 

1. Teleporting to FC Estate - character runs to plot 29 instead of plot 30 in Shirogane.
Entered location paths in Pre-Loop settings for FC Estate.
Tested to see if inputted paths works, does the first time, but doesn't after teleporting again.
Inputs are saved. Will only work after inputting the first time. Second time and beyond doesn't.

2. Stop button greyed out on Menu bar when teleporting to Apartment or FC Estate.

**Comment by VeraNala** [comment]
By some odd stroke of luck I own both plots 29 and 30 in Shirogane.
For me, Plot 30 is my Personal Home while Plot 29 is my FC.

For some odd reason, these two appear to have flipped coordinates for their entrances.
As when I attempt to travel to my FC -> It takes me into my Personal Home
And when I attempt to travel to my Personal Home -> It takes me to my FC.

**Comment by GuyStructure** [comment]
I just logged on another alt that has FC Estate in the Goblet plot 30. Teleports to the correct house, but runs the opposite direction of the FC door. I let it run its path by guiding it along walls and stairs, it went and stopped on the side of plot 5, no where near the door of a house. I now think the bug is more than just Shirogane.
