### ISSUE TITLE
[Bug] Auto Equip Recommended Gear not working between/before loops

### ISSUE THREAD

**Issue by BGFY91** [ffxivcode/AutoDuty#397]
### What happened?

Originally reported here, #355
While the merged PR did manage to fix the `Equip` and `Auto` (leveling option) buttons manually equipping gear upgrades, the feature is still not firing between loops, including before the first loop when pressing `Run`.

### Version Number

156

### Steps to reproduce the error

Have available gear upgrades identifiable by even the native Recommended Gear feature and press `Run`, or finish a loop with another still pending, while having the Auto Equip Recommended Gear option enabled.

**Comment by BGFY91** [comment]
Yes, I can confirm that. Watched it happen not one minute ago, fresh upgrade from previous dungeon in inventory (that upon stopping the loop and pressing `Equip` manually, was equipped).

However, upon testing again I think I may be reporting the issue incorrectly. I don't think it's the Auto Equip itself that is failing, I think the entire Pre-Loop block is being skipped between loops, because it's not eating food either (but it DOES eat when first pressing `Run`). It also zones back into the instance after exiting almost instantly, it definitely doesn't appear to be trying to do anything at all.

This could be related to a similar issue reported recently where the `Enable` checkboxes featured in each section were disabling behavior in others. I currently have the Between Loop block entirely disabled, I'll try checking the Enable checkbox and see if it causes the Pre-Loop actions to fire again.

**Comment by Herculezz55** [comment]
If the between loop config is disabled it will not do anything between loops, even preloop stuff that does also between loops

**Comment by BGFY91** [comment]
@Herculezz55 Well yes, it's a bit confusing that disabling one section would disable actions in another.

This raises a long standing question though, do Auto Equip, Auto Repair, and Auto Consume really belong in the Pre-Loop section? Should they not be moved to the Between Loop section, as that is what they actually do? Either with notes that they will also run before the first loop, or just have everything in the Between Loop section run before starting the first loop (currently AR will not run even if retainers are available, until after completion of the first loop, which is silly).

**Comment by Herculezz55** [comment]
Ya, I will get with Vera and see what we can improve to make that make more sense.
