### ISSUE TITLE
Autoduty issue

### ISSUE THREAD

**Issue by hudorski** [ffxivcode/AutoDuty#400]
### What happened?

Autoduty doesnt work anymore, spawns in does the movement but does not click on any buttons/no rotation. Used to work perfectly fine before this issue, It says it is waitin for combat in the mini menu you get.

### Version Number

v0.0.0.156

### Steps to reproduce the error

I queue into vanguard on war at lvl 98.

**Comment by Aimsucks** [comment]
My man, you need to provide more than "plugin doesn't work" to get help.

**Comment by VeraNala** [comment]
Please ensure your other plugins are up to date -> RSR, BMR/VBM

**Comment by Herculezz55** [comment]
Rotation are RSR / AutoRot, AD does not click any actions for you, Please visit their discord or open an issue on their GitHub for help, ty
