### ISSUE TITLE
[Bug] Game Stuck upon Interacting w/ GC Turn-in NPC

### ISSUE THREAD

**Issue by Katsuvera** [ffxivcode/AutoDuty#401]
### What happened?

I set AD to do a bunch of runs of Doma Castle (with the settings to stop when my NIN reached Lv71 and then kill the client) and then went to bed. I've done this plenty of times before without any issues, however this time I woke up a little while later to see that my NIN was standing in front of the GC turn-in person... And, notably, was still level 69. Also, AD was still technically in the middle of the runs (aka. I had the option to "Stop" or "Pause" AD from running cuz it was still going). With that said, the game appeared to be stuck (and had been stuck for hours). Not, like, totally frozen, mind you: I could still move my camera around and open up UI elements; but I was not able to move my character at all, nor could I click on any NPCs (such as the turn-in NPC) to interact with them (couldn't click on other players, either). It's like I was stuck interacting with the turn-in NPC, but the dialogue window wasn't open, and there was no way to cancel this.

As mentioned, I've run AD a lot overnight and this is the first time it's happened so, like, I'm just hoping it was a random one-off thing with just game's being buggy as games tend to be sometimes, buuuuuut I _was_ able to get a copy of the xllog and it does have some errors at the top so I figured I'd share it here just in case someone who can actually read this can see a glaringly obvious issue.

Thanks for your time. 🙇 

[Game_Stuck_Log.txt](https://github.com/user-attachments/files/16901669/Game_Stuck_Log.txt)

### Version Number

155

### Steps to reproduce the error

Unsure, sorry. Set AD to do a bunch of runs overnight...?

### Relevant log output

```shell
See file attached above.
```

**Comment by Herculezz55** [comment]
Ok, so it looks like something in the game was not allowing AD to interact with the Storm Personell Officer, and Deliveroo for the fact as well since it tries in the same spot, and after 10 mins the timeout stop occured, Im guessing after that it was going to move back to wherever you run your ad from and since the client was movement locked it was unable to do so and just sat there forever. If it happens again reopen this and post the new log. But like you I think this was probably a one off glitch

**Comment by Katsuvera** [comment]
I appreciate you looking into it. As you said, I'll post here if it happens again.
The only thing I'd add, if it matters, is that I always run AD (or, so far, have always run AD) from right in front of the turn-in person. I also repair my own gear, so AD had never had to move anywhere between runs. Maybe it thought it needed to move in this instance tho or something. It is a mystery.

**Comment by Herculezz55** [comment]
hmm interesting ya if you dont need to move it should have moved to the next step, i will try to repro at least see what i can find
