### ISSUE TITLE
[Bug] Boss Action failed to loot Boss Chests after completing Alex - The Eyes of the Creator

### ISSUE THREAD

**Issue by Katsuvera** [ffxivcode/AutoDuty#405]
### What happened?

Alright, first of all, I noticed that the two recent Alexander paths uploaded had TreasureCoffer Actions at the end, after the boss step, which afaik are unnecessary (pls correct me if I'm wrong). I deleted them from the Paths, as well as went to add notes about this to the HelpMarkers, and was preparing to upload a Pull Request. Before I did so, however, I wanted to confirm that AD can actually loot raid boss chests just via the Boss Action, so I did the following:

A.) Ran a run of Alex - The Burden of the Father with just one Boss Action in it (my own path, which I made and then ran from in the instance). It worked fine, beat the boss, and looted the chests.

B.) Queued for and did a run of Fist of the Son using the Path recently uploaded (but without the two TreasureCoffer steps at the end) and it worked just fine. Beat the boss and looted the chests at the end.

C.) Queued for and did a run of Eyes of the Creator using the Path recently uploaded (but without the two TreasureCoffer steps at the end) and it failed. It didn't loot the chests, and instead just left immediately after beating the boss.

Is it perhaps because the boss chests were too far away from my character when the fight it ended...?

Oh also, I went to get the /xllog for the runs I did, and I noticed I'm getting an error repeatedly at certain points. It seems close to the same error seen in the last log I posted (about game stuck) but not exactly the same. But AD seems to be running just fine...? Is it not a big issue? I've attached the log here, I just copied everything about the three runs I did tho, since I wasn't exactly sure what was relevant, sorry. I hope it's not too difficult to parse through. 
[Alex_EyesOfTheCreator_Log.txt](https://github.com/user-attachments/files/16905245/Alex_EyesOfTheCreator_Log.txt)

### Version Number

157

### Steps to reproduce the error

Run Eyes of the Creator path recently uploaded but without the two TreasureCoffer steps at the end.

### Relevant log output

```shell
See log attached above (think it'd be too long to post here).
```

**Comment by Herculezz55** [comment]
Could be it searches a radius of 30, also could be if they didnt spawn for more than 1s after the fight ended then it would miss them as well. I can take a look at that particular one and see what happened
