### ISSUE TITLE
[Bug] Paths not loaded/available in duty; repeat crashing

### ISSUE THREAD

**Issue by ayo-bruh** [ffxivcode/AutoDuty#413]
### What happened?

AD tries to load mesh from last dungeon instead of current one you just entered (ie, trying to load Brayflox Hard in Aetherfont dungeon). going to paths tab and back to main (where steps should be) flashes a 'cant load Brayflox path' (paraphrasing) in green

leaving dungeon then crashes game

then simply trying to load AD again (w/o non-AD related addons) crashed game again, seemingly as it was trying to check for trust levels. (not even getting to point where i could choose dungeon or whatever)

this was repeated again with same crashing sequence when i tried to load

### Version Number

current - 158

### Steps to reproduce the error

see above

### Relevant log output

```shell
nothing relevant/AD related here
```

**Comment by Herculezz55** [comment]
This is an interesting one, I have not experienced this, Also if the game is having errors, the path is not loading or anything like this is should have something in the log file. Could you please try to repro, with log in Debug Mode and Filter set to AD

**Comment by Herculezz55** [comment]
Any update on this?

**Comment by ayo-bruh** [comment]
> This is an interesting one, I have not experienced this, Also if the game is having errors, the path is not loading or anything like this is should have something in the log file. Could you please try to repro, with log in Debug Mode and Filter set to AD

I believe
