### ISSUE TITLE
Unable to set paths with windows restricted characters in duty name

### ISSUE THREAD

**Issue by euonymph** [ffxivcode/AutoDuty#42]
Due to Windows being unable to use ":" in any file names, paths cannot be made for any of the "Minstrel's Ballad: ..." trials or any of the Shadowbringers or Endwalker raid series (Eden's x: ...) (Asphodelos/Abyssos/Anabesios: ...). 

When the plugin attempts to write the path to file it truncates it at the ":", making it unable to be loaded.

As per Vera, if you change the filetype to .json and ignore the truncated text in the paths folder it will show in the trial path menu, but it will ONLY queue for Garuda Ex.

Possibly fixed by adding another String replace method in the Content Helper to substitute a ":" for another character?
Also noticed that there is a typo in the RegularDutyManager.cs IndexMod where the name in case 4 is spelled "The Minstrel's Balad" instead of "The Minstrel's Ballad."

**Comment by adambennett55** [comment]
Fixed in v60
