### ISSUE TITLE
[Bug] GAME CRASH! After new update.

### ISSUE THREAD

**Issue by Yukituki11681** [ffxivcode/AutoDuty#420]
### What happened?

I'm not getting a crashing error of any kind. I simply hit start and it shows support window being uploaded with support npcs and then crash. It's instant. No hang up. No dalamund crash. Nothing.

### Version Number

0.0.0.159

### Steps to reproduce the error

I simply queue into Aery via Duty support set to Support and Levelling set to Auto.

### Relevant log output

```shell
01:36:50.269 | ERR | [Command] Command /rotation not found.
01:36:50.269 | ERR | [Command] Command /rsr not found.


Only thing relevant. No idea if it pertains to the issue. I'm sorry. Super tired.
```

### Other relevant plugins installed

Boss Mod (Non-fork) 0.0.0.233
Rotation Solver Reborn 7.0.5.53

These got updated the same time as Boss Mod

**Comment by SuccessfullRecovery** [comment]
I'm also getting this, same as above.
