### ISSUE TITLE
[Bug] [Multiple Dungeons] - Leaves certain dungeons without engaging last boss

### ISSUE THREAD

**Issue by fifi-ch** [ffxivcode/AutoDuty#428]
### What happened?

AD left the dungeon after the boss cutscene (which was skipped) without engaging the boss.
Affected Dungeons:

* Paglthan
* The Aetherfont
* Mt. Gulg
* The Ghymlit Dark (yeah I made that path, it has an issue entering the boss arena sorry)

There might be more, but these are the ones where I could observe this behavior consistently while going through MSQ on multiple characters.

### Version Number

160

### Steps to reproduce the error

Queue using Duty Support. Observed with DNC.

**Comment by fifi-ch** [comment]
The worst part: it might only happen the first time you are in those dungeons. Just did a re-run of The Aetherfont intending to manually engage the boss and it went through just fine. It's super weird, because the failure rate on a char who has not seen it has been 100% for me on 4 characters so far on each of the listed dungeons.

**Comment by Herculezz55** [comment]
was this on the Testing Version?

**Comment by fifi-ch** [comment]
No this was on release and with lots of versions of the past month, just finally made a ticket about it (though I observed them all most recently in the past week)

**Comment by CacahuetesManu** [comment]
Sohr Khai

**Comment by Herculezz55** [comment]
could you test on the Testing verison, i am not able to repro

**Comment by fifi-ch** [comment]
I'm on a new character, will switch to testing to see if it still happens, prob gonna hit Mt. Gulg in a few hours

**Comment by fifi-ch** [comment]
Totally engaged the final boss in Mt. Gulg gonna be a bit till I get to Aetherfont

**Comment by Herculezz55** [comment]
Any More updates on 163?

**Comment by fifi-ch** [comment]
Was sleeping, just picking up again now starting post-shb, so paglthan up in a few hours.

**Comment by fifi-ch** [comment]
Paglthan is a separate issue of it skipping steps when mounting the dragon. Tbh this is low prio for me I can just continue running latest versions and update or close if it doesn't repro anymore or happens again

**Comment by Herculezz55** [comment]
ok ill close for now, if it comes up you can reopen
