### ISSUE TITLE
[Bug] Auto consume doesn't successfully consume multiple items

### ISSUE THREAD

**Issue by lord2800** [ffxivcode/AutoDuty#431]
### What happened?

I have three items in my auto consume list: superior spiritbond potion, squadron spiritbonding manual, and better crowned pie. When starting, autoduty consumes the first item on the list (superior spiritbond potion) and then immediately attempts to queue for the dungeon while consuming the second item. Because the second item (squadron spiritbonding manual) has a cast time, it fails to apply it, and then skips the third item entirely. In between loops, it never attempts to reapply any of the items except the first.

### Version Number

v0.0.0.160

### Steps to reproduce the error

Add multiple items to the auto consume list, start looping.

### Relevant log output

```shell
None that I see. No errors and no output from attempting to consume between loops.
```

### Other relevant plugins installed

N/A

**Comment by Herculezz55** [comment]
please try this on the testing version, it is working fine for me

**Comment by lord2800** [comment]
Something even more weird, this suddenly started working again _without_ any updates. I'm still on v160 and it works now, for whatever reason.

**Comment by Herculezz55** [comment]
are you sure you dont have testing versions enabled? theres a bug that testing versions dont display the correct version in ad

**Comment by lord2800** [comment]
I do have the testing version enabled, but I hadn't actually performed an update (I was just letting it run). I've just done so now though.

**Comment by lord2800** [comment]
I just started it again after updating, I had 2/3 buffs at the time of starting and it didn't consume the third buff (squad manual).

**Comment by lord2800** [comment]
`/xlplugins` says I have v0.0.0.162 and it's definitely not consuming the squad manual. I just watched it consume a new better crowned pie in the meantime, however. Another half hour before that plus the potion wear off--we'll see what it consumes then.

**Comment by lord2800** [comment]
OK, I stopped things, then dropped all buffs, then started again, and it used the spiritbond potion and the manual, but failed to use the food. It also tried to queue while in the middle of using the manual.

**Comment by lord2800** [comment]
Even more weird: when it went to the inn to handle autoretainer, it consumed the food! I'm now even more confused.
