### ISSUE TITLE
[Feature Request] Including Notes from the "Paths" section in the Main tab drop-down menu

### ISSUE THREAD

**Issue by Katsuvera** [ffxivcode/AutoDuty#433]
### What problem are you trying to fix?

Notes currently only show up in the Paths tab, which I don't believe the average user will see.

![image](https://github.com/user-attachments/assets/c223b8f0-6e97-4a0f-930e-df7eb8b2970b)

### What is the solution to the problem?

Show said Notes while hovering over Paths in the Main tab's drop-down selection menu. Only if this is possible, mind you, and if you don't think it'd be in the way.

**Comment by erdelf** [comment]
Worthy of a thought. So far the notes are unused and I just included them as a barebones idea.
Using them for this.. not a bad idea.
