### ISSUE TITLE
[Bug] Equip sometimes fails to equip upgrades

### ISSUE THREAD

**Issue by BGFY91** [ffxivcode/AutoDuty#434]
### What happened?

This is a somewhat new bug, or at least I'm fairly certain it wasn't happening 20 or so versions ago.

Sometimes, I am still unsure of the exact conditions but it has so far only happened when there are many available upgrades at once, the Equip feature will fail to equip upgrades.
The only time I can 'get it' to happen is when using the Leveling Mode feature. I have an armory chest/inventory stuffed with major level bump upgrades to unlock dungeons because of the ilvl requirement (eg. 89 to 90 for the 91 dungeon), however after exiting a dungeon after reaching this new level, the upgrades are not equipped.
When a new _singular_ upgrade is received from a run, it is always equipped between loop (eg. run dungeon level 93, get ilvl drop, it is equipped before next loop).
I have checked with gearsetter, and the items themselves are definitely detected by it as upgrade options. After starting a new loop after failing to equip all the expected gear, I can run `/gup` and see all the items listed for the set, but they were ignored.
Interesting observation, if I stop the loop and press `Equip`, nothing will happen other than a notice that the gearset has been registered. But if I press the button a second time, all the gear will be equipped as expected. I can't replicate this by taking it all off at once and pressing `Equip` cold, it seems (or seemed, I've had little chance to test) to only happen when gear has already failed to equip.

### Version Number

160

### Steps to reproduce the error

Only potential repro steps I can suggest are to have a job at level X with X+1 level gear available, then run loops that will cause you to level up while the Auto Equip feature is checked. It should fail to equip between loops after reaching the next level but I can't say for sure.
All I can say is that it has happened to me every 10 levels on the two most recent jobs I've been leveling, I need to stop the loops and manually force the gear upgrades or I get indefinitely stuck in low level dungeons that give reduced experience.

**Comment by Herculezz55** [comment]
is this the testing version?

**Comment by BGFY91** [comment]
Whatever the herc repo is supplying by default right now, stamped v0.0.0.160. And I don't have testing builds enabled.
It's also not new to this version, I've been having the problem for a week or so but have been too lazy to report it. I suspect it started happening around the time of #341 being merged, but can't remember for sure if it was earlier or didn't occur immediately afterwards. I also haven't been testing this exact use case every release.
I'd go back and bisect but I have no idea how to install old releases or build/install my own builds.

**Comment by Herculezz55** [comment]
how is your ping normally, could be related to timing?

**Comment by BGFY91** [comment]
It hovers around 12ms. On an unrelated note, I wonder if ping could be why consume doesn't work sometimes?

The Auto Equip feature definitely used to work flawlessly a couple of weeks ago though, so there's definitely some change that has broken it somehow.

**Comment by Herculezz55** [comment]
well i will look into it but tbf, it works for me, but i will see about increasing the time on it but idk y 12ms would cause a problem

**Comment by BGFY91** [comment]
If I can work out a reliable repro other than leveling up naturally with ready available gear I will mention it. It's quite annoying that it has quite a severe impact (leveling needs manual intervention every 10 levels and can't be left unattended), but is also effectively restricted to 'one off' events that can't be reproduced on demand.
