### ISSUE TITLE
Cannot end duty

### ISSUE THREAD

**Issue by yudistiraen** [ffxivcode/AutoDuty#45]
I found this issue after 7.0 dalamud update
when i use Autoduty for leveling my charracter and setting the loop, its not exiting the duty even i have checked `Auto Exit Duty on Completion of Dungeon`

edit : plus im trying to edit the path with addition of `StopForCombat = true` and its still not working

**Comment by adambennett55** [comment]
Maybe sig might have changed, i will research

**Comment by adambennett55** [comment]
v52 - Modified ExitDuty to use UI instead of Sig

**Comment by yudistiraen** [comment]
thankyou for the response, ill try that again and come back if there's still an issue
