### ISSUE TITLE
[Bug] Brayflox longstop hard mode skips a captive goblin softlocking itself

### ISSUE THREAD

**Issue by nathnathn** [ffxivcode/AutoDuty#450]
### What happened?

Brayflox longstop hard mode skips a captive goblin by not waiting for mobs to spawn soft locking itself at the boulder with the default path "only tested as DRK"
i did a quick fix if it helps by adding a few extra nodes that seems to work also added a chest that was forgotten but couldnt add the last one as path finding doesn't seem to be able to handle that tower particularly well.
[(362) Brayflox's Longstop (Hard) test1 add chests fix issues.json](https://github.com/user-attachments/files/17002595/362.Brayflox.s.Longstop.Hard.test1.add.chests.fix.issues.json)

### Version Number

0.0.0.160

### Steps to reproduce the error

run default route as DRK with bossmod for rotation solver.

### Other relevant plugins installed

Boss Mod 0.0.0.239

**Comment by Herculezz55** [comment]
Fixed in Relase 171
