### ISSUE TITLE
Move to bugged

### ISSUE THREAD

**Issue by Eykishou** [ffxivcode/AutoDuty#467]
What Happened?

https://discord.com/channels/1001823907193552978/1236757595738476725/1285736564173045791

Same problem as this person,  I start the loop and my character won't move. I does use standard step but the "move to" actions are skipped and it switches directly to boss.

Version Number

166

Steps to reproduce the error

just start a loop in any dungeon

Relevant log output

2024-09-18 14:23:28.283 +02:00 [INF] [AutoDuty] Running AutoDuty in The Sirensong Sea, Looping 1 times
2024-09-18 14:23:28.284 +02:00 [INF] [AutoDuty] Running The Sirensong Sea 1 Times
2024-09-18 14:23:28.343 +02:00 [INF] [AutoDuty] Queueing: Regular: The Sirensong Sea
2024-09-18 14:23:31.819 +02:00 [INF] [AutoDuty] Done Queueing: Regular: The Sirensong Sea
2024-09-18 14:23:37.983 +02:00 [INF] [AutoDuty] Starting Navigation
2024-09-18 14:23:56.431 +02:00 [INF] [AutoDuty] Starting Action Boss: null
2024-09-18 14:24:29.020 +02:00 [INF] [AutoDuty] Starting Action Boss: null
2024-09-18 14:25:01.353 +02:00 [INF] [AutoDuty] Starting Action Boss: null
2024-09-18 14:25:33.640 +02:00 [INF] [AutoDuty] ExitDuty Started
2024-09-18 14:25:36.775 +02:00 [INF] [AutoDuty] ExitDuty Finished

Other relevant plugins installed

Penumbra, Version= 1.2.1.4
PatMe, Version= 1.10.1.0
NecroLens, Version= 1.0.7.12
QoLBar, Version= 2.3.3.0
OOBlugin, Version= 1.1.2.11
XIVCombo, Version= 1.8.5.0
TPie, Version= 1.9.1.0
Ktisis, Version= 0.2.26
Kapture, Version= 1.8.0.0
HoardFarm, Version= 1.5.2.9
Gearsetter, Version= 1.3
MiniCactpotSolver, Version= 2.0.0.1
PennyPincher, Version= 1.8.0.0
FPSPlugin, Version= 1.7.0.0
Visibility, Version= 1.1.7.5
SkipCutscene, Version= 1.2.2.4
WondrousTailsSolver, Version= 3.1.0.4
BigPlayerDebuffs, Version= 1.1.0.10
autoSweep, Version= 1.4.5.0
MimicryHelper, Version= 1.0.1.4
CollectableCalculator, Version= 3.0
NamePlateDebuffs, Version= 1.1.0.3
Workshoppa, Version= 6.2
PushyFinder, Version= 1.3.0.0
Marketbuddy, Version= 0.2.3.1
ReSanctuary, Version= 1.4.0.0
TargetFurniture, Version= 1.0.2.0
AntiAfkKick-Dalamud, Version= 2.1.0.6
TeleporterPlugin, Version= 2.0.2.4
TriadBuddy, Version= 1.10.0.1
BDTHPlugin, Version= 1.6.6
Deliveroo, Version= 5.5
Brio, Version= 0.4.1
BlueMageHelper, Version= 3.0.2.0
PeepingTom, Version= 1.7.17
Umbra, Version= 2.2.36.0
Moodles, Version= 1.0.0.27
SimpleTweaksPlugin, Version= 1.10.1.1
FCNameColor, Version= 5.0.1.0
LazyLoot, Version= 5.3.0.2
Lifestream, Version= 2.2.1.3
AutoRetainer, Version= 4.4.0.2
visland, Version= 0.0.0.118
EnemyListDebuffs, Version= 0.4.0.3
MareSynchronos, Version= 0.10.10
MarketBoardPlugin, Version= 1.8.0.0
heliosphere-plugin, Version= 2.3.1.0
MacroChain, Version= 2.2.0.0
HighFpsPhysicsPlugin, Version= 8.0.1.0
Globetrotter, Version= 1.2.11
PriceInsight, Version= 2.11.0.0
XIVComboExpandedest, Version= 1.5.0.68
Saucy, Version= 1.4.0.3
AutoHook, Version= 4.3.0.12
MidiBard2, Version= 2.6.1.0
ChatBubbles, Version= 2.1.7.1
Honorific, Version= 1.5.0.1
YesAlready, Version= 1.7.2
Questionable, Version= 3.3
vnavmesh, Version= 0.0.0.41
SimpleHeels, Version= 0.10.1.1
RotationSolver, Version= 7.0.5.88
NoClippy, Version= 0.5.0.16
PandorasBox, Version= 1.6.1.0
CustomizePlus, Version= 2.0.6.2
Cammy, Version= 2.1.0.9
MakePlacePlugin, Version= 3.6.2
DistantSeas, Version= 1.1.0.1
GatherbuddyReborn, Version= 7.2.1.8
BossModReborn, Version= 7.2.0.132
Artisan, Version= 4.0.1.8
Glamourer, Version= 1.3.1.1
InventoryTools, Version= 1.7.0.20
SomethingNeedDoing, Version= 1.42
AutoDuty, Version= 0.0.0.167

Config file

{
  "$type": "AutoDuty.Windows.Configuration, AutoDuty",
  "DoNotUpdatePathFiles": [],
  "PathSelections": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.Dictionary`2[[ECommons.ExcelServices.Job, ECommons],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "AutoScroll": true,
  "LogEventLevel": 1,
  "LoopTimes": 1,
  "Unsynced": true,
  "HideUnavailableDuties": true,
  "ShowMainWindowOnStartup": false,
  "ShowDutyLoopText": true,
  "ShowActionText": true,
  "UseSliderInputs": false,
  "OverrideOverlayButtons": true,
  "GotoButton": true,
  "TurninButton": true,
  "DesynthButton": true,
  "ExtractButton": true,
  "RepairButton": true,
  "EquipButton": true,
  "AutoExitDuty": true,
  "AutoManageRotationPluginState": true,
  "AutoManageVnavAlignCamera": true,
  "LootTreasure": true,
  "LootMethodEnum": 0,
  "LootBossTreasureOnly": false,
  "TreasureCofferScanDistance": 25,
  "OverridePartyValidation": false,
  "UsingAlternativeRotationPlugin": false,
  "UsingAlternativeMovementPlugin": false,
  "UsingAlternativeBossPlugin": false,
  "EnablePreLoopActions": true,
  "ExecuteCommandsPreLoop": false,
  "CustomCommandsPreLoop": [],
  "RetireMode": false,
  "RetireLocationEnum": 0,
  "PersonalHomeEntrancePath": [],
  "FCEstateEntrancePath": [],
  "AutoEquipRecommendedGear": false,
  "AutoEquipRecommendedGearGearsetter": false,
  "AutoRepair": true,
  "AutoRepairPct": 25,
  "AutoRepairSelf": true,
  "PreferredRepairNPC": null,
  "AutoConsume": false,
  "AutoConsumeIgnoreStatus": false,
  "AutoConsumeItemsList": [],
  "EnableBetweenLoopActions": true,
  "WaitTimeBeforeAfterLoopActions": 0,
  "AutoExtract": false,
  "AutoGCTurninSlotsLeft": 5,
  "AutoGCTurninSlotsLeftBool": false,
  "AutoGCTurninUseTicket": false,
  "EnableAutoRetainer": false,
  "PreferredSummoningBellEnum": 0,
  "AM": false,
  "UnhideAM": false,
  "EnableTerminationActions": true,
  "StopLevel": false,
  "StopLevelInt": 1,
  "StopNoRestedXP": false,
  "StopItemQty": false,
  "StopItemQtyItemDictionary": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "StopItemQtyInt": 1,
  "ExecuteCommandsTermination": false,
  "CustomCommandsTermination": [],
  "PlayEndSound": false,
  "CustomSound": false,
  "CustomSoundVolume": 0.5,
  "SoundEnum": 0,
  "SoundPath": "",
  "TerminationMethodEnum": 0,
  "TerminationKeepActive": true,
  "HideBossModAIConfig": false,
  "FollowDuringCombat": true,
  "FollowDuringActiveBossModule": true,
  "FollowOutOfCombat": false,
  "FollowTarget": true,
  "FollowSlotInt": 1,
  "FollowRoleEnum": 1,
  "MaxDistanceToTargetFloat": 10.0,
  "MaxDistanceToTargetAoEFloat": 2.6,
  "MaxDistanceToSlotFloat": 1.0,
  "PositionalEnum": 0,
  "SelectedTrustMembers": [
    null,
    null,
    null
  ],
  "Version": 166,
  "DutyModeEnum": 8,
  "ShowOverlay": true,
  "HideOverlayWhenStopped": false,
  "LockOverlay": false,
  "OverlayNoBG": false,
  "AutoManageBossModAISettings": true,
  "AutoExtractAll": false,
  "AutoDesynth": false,
  "AutoDesynthSkillUp": false,
  "AutoGCTurnin": true,
  "FollowSelf": true,
  "FollowSlot": false,
  "FollowRole": false,
  "MaxDistanceToTargetRoleBased": true,
  "PositionalRoleBased": true
}

**Comment by Herculezz55** [comment]
please attach me the path file that is doing this to this comment by clicking the paperclip

**Comment by Eykishou** [comment]
[(1142) The Sirensong Sea.json](https://github.com/user-attachments/files/17066239/1142.The.Sirensong.Sea.json)

but i actually reinstalled the plugin and ever since it's working
