### ISSUE TITLE
[Bug] navmesh issue, no path found in limsa lominsa upper decks

### ISSUE THREAD

**Issue by Estriam** [ffxivcode/AutoDuty#472]
### What happened?

The plugins seems to be unable to find paths in Limsa Lominsa upper decks from the aftcastle aethernet to the inn or grand company. While in duty there is no such issue. Rebuilding navmesh did not seem to fix the issue.
![Capture d'écran 2024-09-20 133552](https://github.com/user-attachments/assets/2d8b5fe5-7a4c-4c4f-a8bf-c6350175ef14)

### Version Number

v0.0.0.168

### Steps to reproduce the error

run anything that goes by the aftcastle

### Relevant log output

```shell
14:26:52.297 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.297 | ERR | [vnavmesh] Failed to find a path from <5.365111, 39.6112, 11.070585> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.334 | INF | [vnavmesh] Pathfinding complete
14:26:52.368 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.368 | ERR | [vnavmesh] Failed to find a path from <5.8422823, 39.7584, 10.785652> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.405 | INF | [vnavmesh] Pathfinding complete
14:26:52.440 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.440 | ERR | [vnavmesh] Failed to find a path from <6.3226323, 39.756386, 10.498821> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.477 | INF | [vnavmesh] Pathfinding complete
14:26:52.511 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.511 | ERR | [vnavmesh] Failed to find a path from <6.8076687, 39.754402, 10.223166> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.546 | INF | [vnavmesh] Pathfinding complete
14:26:52.581 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.581 | ERR | [vnavmesh] Failed to find a path from <7.2854757, 39.771843, 9.977176> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.617 | INF | [vnavmesh] Pathfinding complete
14:26:52.652 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.652 | ERR | [vnavmesh] Failed to find a path from <7.7780175, 39.906498, 9.726838> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.687 | INF | [vnavmesh] Pathfinding complete
14:26:52.722 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.722 | ERR | [vnavmesh] Failed to find a path from <8.280971, 39.99985, 9.503009> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.758 | INF | [vnavmesh] Pathfinding complete
14:26:52.793 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.793 | ERR | [vnavmesh] Failed to find a path from <8.81298, 40, 9.34622> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
14:26:52.829 | INF | [vnavmesh] Pathfinding complete
14:26:52.865 | INF | [vnavmesh] Queueing move-to <15.427, 40.000, 12.467>
14:26:52.865 | ERR | [vnavmesh] Failed to find a path from <9.341797, 39.999992, 9.205104> (0) to <15.42688, 39.99999, 12.466553> (0): failed to find polygon on a mesh
```

### Other relevant plugins installed

vnavlesh
bossmode
automaton
autoretainer
orbwalker
snb
visland

### Plugin config file

{
  "$type": "AutoDuty.Windows.Configuration, AutoDuty",
  "DoNotUpdatePathFiles": [],
  "PathSelections": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.Dictionary`2[[ECommons.ExcelServices.Job, ECommons],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "AutoScroll": true,
  "LogEventLevel": 1,
  "LoopTimes": 10,
  "Unsynced": true,
  "HideUnavailableDuties": false,
  "ShowMainWindowOnStartup": false,
  "ShowDutyLoopText": true,
  "ShowActionText": false,
  "UseSliderInputs": false,
  "OverrideOverlayButtons": true,
  "GotoButton": true,
  "TurninButton": true,
  "DesynthButton": true,
  "ExtractButton": true,
  "RepairButton": true,
  "EquipButton": true,
  "AutoExitDuty": true,
  "AutoManageRotationPluginState": true,
  "AutoManageVnavAlignCamera": true,
  "LootTreasure": true,
  "LootMethodEnum": 0,
  "LootBossTreasureOnly": false,
  "TreasureCofferScanDistance": 25,
  "OverridePartyValidation": false,
  "UsingAlternativeRotationPlugin": false,
  "UsingAlternativeMovementPlugin": false,
  "UsingAlternativeBossPlugin": false,
  "EnablePreLoopActions": true,
  "ExecuteCommandsPreLoop": false,
  "CustomCommandsPreLoop": [],
  "RetireMode": true,
  "RetireLocationEnum": 0,
  "PersonalHomeEntrancePath": [],
  "FCEstateEntrancePath": [],
  "AutoEquipRecommendedGear": true,
  "AutoEquipRecommendedGearGearsetter": false,
  "AutoRepair": true,
  "AutoRepairPct": 50,
  "AutoRepairSelf": false,
  "PreferredRepairNPC": {
    "$type": "AutoDuty.Helpers.RepairNPCHelper+RepairNpcData, AutoDuty",
    "RepairIndex": 0,
    "DataId": 1001206,
    "Name": "Alistair",
    "TerritoryType": 129,
    "Position": {
      "$type": "System.Numerics.Vector3, System.Private.CoreLib",
      "X": -247.12,
      "Y": 16.1898,
      "Z": 51.8654
    }
  },
  "AutoConsume": false,
  "AutoConsumeIgnoreStatus": false,
  "AutoConsumeItemsList": [],
  "EnableBetweenLoopActions": true,
  "WaitTimeBeforeAfterLoopActions": 0,
  "AutoExtract": true,
  "AutoGCTurninSlotsLeft": 10,
  "AutoGCTurninSlotsLeftBool": false,
  "AutoGCTurninUseTicket": true,
  "EnableAutoRetainer": true,
  "PreferredSummoningBellEnum": 0,
  "AM": false,
  "UnhideAM": false,
  "EnableTerminationActions": true,
  "StopLevel": false,
  "StopLevelInt": 1,
  "StopNoRestedXP": false,
  "StopItemQty": false,
  "StopItemQtyItemDictionary": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "StopItemQtyInt": 1,
  "ExecuteCommandsTermination": false,
  "CustomCommandsTermination": [],
  "PlayEndSound": false,
  "CustomSound": false,
  "CustomSoundVolume": 0.5,
  "SoundEnum": 0,
  "SoundPath": "",
  "TerminationMethodEnum": 0,
  "TerminationKeepActive": false,
  "HideBossModAIConfig": false,
  "FollowDuringCombat": true,
  "FollowDuringActiveBossModule": true,
  "FollowOutOfCombat": false,
  "FollowTarget": true,
  "FollowSlotInt": 1,
  "FollowRoleEnum": 1,
  "MaxDistanceToTargetFloat": 2.6,
  "MaxDistanceToTargetAoEFloat": 2.6,
  "MaxDistanceToSlotFloat": 1.0,
  "PositionalEnum": 2,
  "SelectedTrustMembers": [
    1,
    2,
    3
  ],
  "Version": 168,
  "DutyModeEnum": 2,
  "ShowOverlay": true,
  "HideOverlayWhenStopped": false,
  "LockOverlay": false,
  "OverlayNoBG": false,
  "AutoManageBossModAISettings": true,
  "AutoExtractAll": false,
  "AutoDesynth": false,
  "AutoDesynthSkillUp": false,
  "AutoGCTurnin": false,
  "FollowSelf": true,
  "FollowSlot": false,
  "FollowRole": false,
  "MaxDistanceToTargetRoleBased": true,
  "PositionalRoleBased": true
}

**Comment by Herculezz55** [comment]
this is a vnav issue, try deleting your cache and remeshing
