### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jalkout** [ffxivcode/AutoDuty#474]
### What happened?

Having random crashes here and there while using Autoduty

### Version Number

0.0.0.168

### Steps to reproduce the error

Simply running autoduty for support dungeons, sometimes it gets to do 22 loops of support (leveling) dungeons without crashes, sometimes it crashes during 1 or after a few.

### Relevant log output

```shell
N/A
```

### Other relevant plugins installed

Bossmode Reborn
Rotation Sovler Reborn
Deliveroo
Pandora
AntiAfkKick
Vnavmesh

### Plugin config file

{
  "$type": "AutoDuty.Windows.Configuration, AutoDuty",
  "DoNotUpdatePathFiles": [],
  "PathSelections": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.Dictionary`2[[ECommons.ExcelServices.Job, ECommons],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "AutoScroll": true,
  "LogEventLevel": 1,
  "LoopTimes": 1,
  "Unsynced": false,
  "HideUnavailableDuties": false,
  "ShowMainWindowOnStartup": false,
  "ShowDutyLoopText": true,
  "ShowActionText": true,
  "UseSliderInputs": false,
  "OverrideOverlayButtons": true,
  "GotoButton": true,
  "TurninButton": true,
  "DesynthButton": true,
  "ExtractButton": true,
  "RepairButton": true,
  "EquipButton": true,
  "AutoExitDuty": true,
  "AutoManageRotationPluginState": true,
  "AutoManageVnavAlignCamera": true,
  "LootTreasure": true,
  "LootMethodEnum": 0,
  "LootBossTreasureOnly": false,
  "TreasureCofferScanDistance": 25,
  "OverridePartyValidation": false,
  "UsingAlternativeRotationPlugin": false,
  "UsingAlternativeMovementPlugin": false,
  "UsingAlternativeBossPlugin": false,
  "EnablePreLoopActions": true,
  "ExecuteCommandsPreLoop": false,
  "CustomCommandsPreLoop": [],
  "RetireMode": false,
  "RetireLocationEnum": 0,
  "PersonalHomeEntrancePath": [],
  "FCEstateEntrancePath": [],
  "AutoEquipRecommendedGear": true,
  "AutoEquipRecommendedGearGearsetter": false,
  "AutoRepair": true,
  "AutoRepairPct": 50,
  "AutoRepairSelf": false,
  "PreferredRepairNPC": null,
  "AutoConsume": false,
  "AutoConsumeIgnoreStatus": false,
  "AutoConsumeItemsList": [],
  "EnableBetweenLoopActions": true,
  "WaitTimeBeforeAfterLoopActions": 0,
  "AutoExtract": false,
  "AutoGCTurninSlotsLeft": 5,
  "AutoGCTurninSlotsLeftBool": false,
  "AutoGCTurninUseTicket": false,
  "EnableAutoRetainer": true,
  "PreferredSummoningBellEnum": 0,
  "AM": false,
  "UnhideAM": false,
  "EnableTerminationActions": true,
  "StopLevel": true,
  "StopLevelInt": 90,
  "StopNoRestedXP": false,
  "StopItemQty": false,
  "StopItemQtyItemDictionary": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "StopItemQtyInt": 1,
  "ExecuteCommandsTermination": false,
  "CustomCommandsTermination": [],
  "PlayEndSound": false,
  "CustomSound": false,
  "CustomSoundVolume": 0.5,
  "SoundEnum": 0,
  "SoundPath": "",
  "TerminationMethodEnum": 0,
  "TerminationKeepActive": true,
  "HideBossModAIConfig": false,
  "FollowDuringCombat": true,
  "FollowDuringActiveBossModule": true,
  "FollowOutOfCombat": false,
  "FollowTarget": true,
  "FollowSlotInt": 1,
  "FollowRoleEnum": 1,
  "MaxDistanceToTargetFloat": 2.6,
  "MaxDistanceToTargetAoEFloat": 2.6,
  "MaxDistanceToSlotFloat": 1.0,
  "PositionalEnum": 0,
  "SelectedTrustMembers": [
    1,
    2,
    6
  ],
  "Version": 168,
  "DutyModeEnum": 0,
  "ShowOverlay": true,
  "HideOverlayWhenStopped": false,
  "LockOverlay": false,
  "OverlayNoBG": false,
  "AutoManageBossModAISettings": true,
  "AutoExtractAll": false,
  "AutoDesynth": false,
  "AutoDesynthSkillUp": false,
  "AutoGCTurnin": true,
  "FollowSelf": true,
  "FollowSlot": false,
  "FollowRole": false,
  "MaxDistanceToTargetRoleBased": true,
  "PositionalRoleBased": true
}

**Comment by jalkout** [comment]
![Screenshot 2024-09-21 011209](https://github.com/user-attachments/assets/7ab56615-4906-4ea5-be64-c1669c6f701c)
managed to get this

your help is highly appreciated

**Comment by jalkout** [comment]
https://drive.google.com/file/d/1mwLImCO5iL6004malD5fQJlYj5hfJQpn/view?usp=sharing


and here is the crash log

**Comment by Herculezz55** [comment]
nothing in this points to autoduty there is not even a log entry for autoduty, if you can get me more to go off of please feel free to reopen
