### ISSUE TITLE
[Bug] Skipping Steps Path 1037 The Tam-Tara Deepcroft

### ISSUE THREAD

**Issue by Matsuuzo** [ffxivcode/AutoDuty#477]
### What happened?

While leveling and entering Tam-Tara it instantly skips Steps up until the Final Boss and then leaves the Dungeon to do the Same Loop. 

After re installing it does the Path "normally" but gets stuck on the 1st Cultist Orb. After a few loops it skips the Steps again.
![Bild_2024-09-23_173616565](https://github.com/user-attachments/assets/9d60bae4-2ca7-4297-abe5-7d109bee3c92)

### Version Number

v0.0.0.169

### Steps to reproduce the error

Queue for Tam-Tara Deepcroft with Leveling I guess?

**Comment by Herculezz55** [comment]
can not repro and we need more info than this, please upload a dalamud.log file
