### ISSUE TITLE
[Bug] Stuck on menues

### ISSUE THREAD

**Issue by SHOEGAZEssb** [ffxivcode/AutoDuty#49]
Since 7.0 the plugin isnt able to click through menues.
For example in the barracks its just stuck on the Menue where you would choose between Command or Squadron missions.
Did some dependency change that I need?

**Comment by MrHappy8D** [comment]
This should be resolved now, let me know if the issue remains. I might also look to see if I can get the seal turn in to work as I was having issues with it as well.

**Comment by adambennett55** [comment]
Fixed in v57
