### ISSUE TITLE
[Bug] Saving after clear path causes crash to desktop

### ISSUE THREAD

**Issue by Tiroth** [ffxivcode/AutoDuty#494]
### What happened?

I was trying to start over building a path and hit clear path, then save path, then clicked the paths tab and crashed

### Version Number

170

### Steps to reproduce the error

press clear path, save path, and click the paths tab or try to run the path

**Comment by Holyone01** [comment]
Created a Path. Saved it it crashed to Desktop. Now when i click on Path it crashes to desktop.

Same bug for me I think.
