### ISSUE TITLE
[Bug] Plugin starts wrong duty

### ISSUE THREAD

**Issue by Naridar** [ffxivcode/AutoDuty#56]
Since 13/07/2024, the plugin doesn't start the selected duty in some occasions.

Based on what I've tried, pre-Shadowbringers duties launch instead the previous one on the list, and the character doesn't start moving when the duty commences. What I've tried to start and what starts instead.

Snowcloak -> The Porta Decumana
The Sirensong sea -> Baelsar's wall
Bardam's mettle -> The sirensong sea
Doma castle -> Bardam's mettle

It is possibly an indexing issue?

**Comment by adambennett55** [comment]
this should be fixed in v54, if its still any issue please reopen
