### ISSUE TITLE
Stuck at LV91 dungeon

### ISSUE THREAD

**Issue by Helchakan** [ffxivcode/AutoDuty#61]
Pathing sometimes is not waiting for the raft to stop and the door to open, so it walks into the wall and get stucks in the raft corner for the whole lockout duration.
Seems to be happening about 50% of the time, autoduty just waits for lockout to end and then starts again.

**Comment by adambennett55** [comment]
This is more of a path issue, I will defer this to whomever made the path

**Comment by chaosgobbie** [comment]
The adjustment below should solve this.

It shifts the MoveTo point before the jump off to the other side of the gate making it impossible to trigger the automove until after the gate is open.  If for some reason the Waits end before the event is over, you will just run at the gate until it opens, then hop off the boat as intended.

Tested as written below and with shorter waits to mimic the described situation.  It's also the method and point I was using before VeraNala's paths were included in the release.

(1167) Ihuykatumu.json
["Wait|-69.09, -194.00, -33.12|10000","Wait|-68.83, -194.00, -32.44|20000","Wait|-69.54, -194.00, -31.01|15000","Wait|-69.05, -194.00, -31.49|30000","Wait|-73.36, -194.00, -30.75|45000","MoveTo|-59.19, -194.17, -31.57|","ChatCommand|0, 0, 0|/automove on boat","Wait|0, 0, 0|2000","ChatCommand|0, 0, 0|/automove off","Boss|33.57, -202.93, -70.30| CP1","Boss|34.61, -203.00, -97.09|","MoveTo|150.12, -195.07, -20.24|","MoveTo|153.93, -195.20, -21.66|","ChatCommand|0, 0, 0|/automove on lad1","Wait|0, 0, 0|10000","Wait|203.71, -158.62, 104.86|3000","MoveTo|202.74, -158.66, 116.73|","Wait|140.82, -155.18, 110.85|2000","MoveTo|129.91, -154.36, 112.14|","ChatCommand|0, 0, 0|/automove on lad2","Wait|0, 0, 0|9500","Boss|81.93, -134.49, 86.29| CP2","Boss|80.00, -134.00, 48.50|","MoveTo|67.05, -134.00, 40.84|","MoveTo|44.76, -132.27, 37.23|","MoveTo|38.03, -130.60, 36.60|","ChatCommand|0, 0, 0|/automove on lad3","Wait|0, 0, 0|8500","MoveTo|11.05, -110.84, 149.36|","MoveTo|-97.43, -115.19, 336.73|","Boss|-106.73, -115.13, 294.72| CP3","Boss|-107.10, -118.00, 262.50|"]

**Comment by adambennett55** [comment]
v62 - Fixed - Stuck at LV91 dungeon
#61 by Helchakan
