### ISSUE TITLE
[Feature Request] Job Level Manager

### ISSUE THREAD

**Issue by Q023** [ffxivcode/AutoDuty#611]
### What problem are you trying to fix?

Leveling multiple jobs automatically without needing to manually switch each time you hit a target level. For instance, if you have five jobs at level 99 and want to level them to 100, the job manager would allow you to set all five jobs, hit run, and let the system handle it without further input.

### What is the solution to the problem?

A "job level manager" feature could allow players to set specific level targets for multiple jobs. For example, you could set WHM to level 85, GNB to level 90, and RPR to level 100. Once WHM reaches 85, AD would automatically switch to GNB and level it up to 90, then switch to RPR and continue to 100. This would automate the leveling process and improve efficiency.

Since we already have the option to set a level cap where AD stops, I believe this feature would be a natural extension, and we're halfway there.

**Comment by erdelf** [comment]
Can't speak for Herc, but my vote on that is no. 
There's enough automation as is in that regard. 
I think it can be expected to interact with your game every dozen hours or so.

**Comment by Herculezz55** [comment]
Agreed with @erdelf
