### ISSUE TITLE
[Bug] ItemCount not working in ConditionAction

### ISSUE THREAD

**Issue by chenjr0719** [ffxivcode/AutoDuty#612]
### What happened?

In the `(1041) Brayflox's Longstop`, we need to interact with a NPC to get the event item. The path file will check the event item is exist or it will keep interact with that NPC and get stucked.

Checked the path file, it passed the operation as the 3rd arg and the quantity as 4th arg:
https://github.com/ffxivcode/AutoDuty/blob/f05bb6134953b5b2391456197db88215f7f46ce9/AutoDuty/Paths/(1041)%20Brayflox's%20Longstop.json#L38

And it looks like not align the usage of `ConditionAction`:
https://github.com/ffxivcode/AutoDuty/blob/f05bb6134953b5b2391456197db88215f7f46ce9/AutoDuty/Managers/ActionsManager.cs#L118-L119

The `ConditionAction` received operation and quantity from the 3rd arg which might be a bug I think.

### Version Number

v0.0.0.172

### Steps to reproduce the error

1. Open the AutoDuty and start with `(1041) Brayflox's Longstop`
2. Waiting for the first combat ends and move to the target NPC
3. Keep interact with NPC and never move to the next step

**Comment by Herculezz55** [comment]
yes you are right, but its not the path file thats incorrect, line 120 needs to be changed too: if (!uint.TryParse(conditionArray[3], out var quantity)) return;   this will be changed for the next release, thanks for the catch
