### ISSUE TITLE
[Bug] Memory Leak and weird behaviour multiboxing.

### ISSUE THREAD

**Issue by McVaxius** [ffxivcode/AutoDuty#613]
### What happened?

ok so here is what we have done
https://github.com/Jaksuhn/SomethingNeedDoing/tree/master/Community%20Scripts/Dungeons/AutoDuty%20Helpers

that link contains the solution we created for multiboxing prae

We have mogtome event and some of us want to multibox it.

Essentially -> 

1. Relying on AD to auto queue doesn't work because if it fails to queue even one time. it will never try again so chars leaving duty at various times will cause it to fail. We solved this by using Automaton to autoque instead, but this turned out to also be a problem because we couldn't repair. so we resorted to SND instead (see above link for script  the long named one that is basically GOON.lua).  This works ok.  basically it retries every 10 seconds while not in duty

2. Entering the duty and /ad start, does not always work so we are using automaton to run a script on duty entry (start_gooning.lua from above link) to /ad stop and /ad start after charisready()

3. after some time. routes are not respected and chars will just skip steps and try to path through floors and ceilings, obviously failing.   we have alot of theories why this happens. and sometimes disabling AD and re enabling fixes it. resetting client definately fixes it for a few hours at least.

4. after some time. interactions take up like 99% cpu and slow the game down to 0 fps and in some cases like the first magitek terminal in PRAE it will reverse interact as it will already be on the other side before the game finishes processing the subarea transition and then you are sent back to the start subarea and the pathing fails.

for 3 & 4, we notice this happens once we change jobs.....but not always. so maybe not related.

5. sometimes during combat, AD will try to force nav around instand of engaging in combat.  We solved this by forcing /vnav stop, (via above script) if we are in GetCharacterCondition(26)

6. if routes are started too quickly in a duty sometimes they will just leave the duty instead (!?!??!) we solved this by handling duty start with SND and then calling ad stop and ad start after some conditions are met (start_gooning.lua)

7. some things we did in the script -> targeting the clones in  phase 2 of hte gauis fight based on some rules.  returning to area entrance and restarting nav if we are not moving more than 3 yalms for 30 seconds or so while not in combat.  pausing yess already and instantly force disabling queue including opening the queue window if its minimized. so that repairs can be accomplished via npc or self

8. sometimes the routing will just not respond to anything . even /ad stop will not stop it and /vnav stop will not stop it. the only way to stop it is if we disable AD the plugin itself. i have videos of this ill share via discord DM.  maybe this is a bug?

### Version Number

2014 10 17

### Steps to reproduce the error

read above

### Relevant log output

```shell
.
```

### Other relevant plugins installed

.

### Plugin config file

.

**Comment by McVaxius** [comment]
i have latest versions of all plugins
MBT is not installed.
using default settings per AD for boss mod, yesalready is on

**Comment by McVaxius** [comment]
turning  /xllog to fatal+ opnly seems to make it more stable for more hours

i believe someone mentioned that xllog was getting filled really hard by errors

**Comment by McVaxius** [comment]
![image](https://github.com/user-attachments/assets/56b18b70-2b15-43dc-a75c-98d2fa2fc3e7)

**Comment by McVaxius** [comment]
what would solve alot of problems would be
1 -> autoqueue to retry on its own
2 -> consideration of multiboxing so force disabling queues so traversal between subareas inn<-->city for repairs is possible
3-> resuming waypoints after a fight or when its "lost" in a corner somewhere.

**Comment by erdelf** [comment]
> Relying on AD to auto queue doesn't work because if it fails to queue even one time.

Trying to debug even one thing here is gonna be difficult if your very start is with a broken setup.

**Comment by McVaxius** [comment]
![image](https://github.com/user-attachments/assets/1edd1729-50f6-45ae-8404-ba56378523f6)
he doesnt ahve git account

**Comment by AkashaXIV** [comment]
Hi. I have git account now.
![Screenshot (31280)](https://github.com/user-attachments/assets/0a097024-83a5-42fb-8fa7-b00750f343b3)
The "GCD Corruption" turned out to be... trying to spam Magitek Cannon. It's showing up under BossModReborn (and would for regular BossMod) because that's from its ping-based anim lock removal.

**Comment by McVaxius** [comment]
just an update . once the interaction 99% cpu problem shows up it never goes away. needs a client restart

**Comment by McVaxius** [comment]
oh i see so its the duty specifc code that starts and never stops ..?

**Comment by AkashaXIV** [comment]
It seems like it's caused when something breaks between DutySpecificCode|1 and Duty Specific Code|2, including pausing or stopping AutoDuty. Going back through them doesn't reverse the issue.

**Comment by McVaxius** [comment]
toggling autoduty disabled/enabled seems to fix the skill spamming issue but the pathing problems pesrist

**Comment by McVaxius** [comment]
interaction delay problem seems to have gone away. so it was another plugin causing that over time thats resolved now

**Comment by McVaxius** [comment]
magitech spam problem gone away. its more or less solid now . im gonna close this unless we find more issues. then we can make a new thread

great work erdelf and herculezz
