### ISSUE TITLE
[Bug] Keep dying on the second boss of Worqor Zormor as BLM

### ISSUE THREAD

**Issue by Luysita** [ffxivcode/AutoDuty#615]
### What happened?

On the crystal part, the characters just keeps attacking the boss and the crystal keeps growing until it kills me.

![2024 10 22-14-48-42](https://github.com/user-attachments/assets/dd575e64-e1ca-4a23-8e65-306bf410904d)

![2024 10 22-15-05-31](https://github.com/user-attachments/assets/e37e3ad5-1602-4b30-9a13-3fe0d599a460)

### Version Number

0.0.0.172

### Steps to reproduce the error

Run Worqor Zormor
Run as Black Mage
Run Path ![2024 10 22-15-24-24](https://github.com/user-attachments/assets/6589ee20-26a9-4e0a-9f25-b36833f51ca5)

Happens when covered with crystal shards

### Relevant log output

```shell
2024-10-22 15:03:36.347 +01:00 [INF] [AutoDuty] Starting Action Boss: Kahderyor
2024-10-22 15:05:36.543 +01:00 [INF] [AutoDuty] Finding Revival Point
2024-10-22 15:05:47.538 +01:00 [INF] [AutoDuty] Starting Action Boss: Kahderyor
```

### Other relevant plugins installed

AdventurerInNeed
AntiAfkKick-Dalamud
Artisan
AutoDuty
AutoHook
Automaton
AutoRetainer
BossMod
DistantSeas
GatherBuddy
GatherbuddyReborn
HuntTrainAssistant
Lifestream
MarketBoardPlugin
MiniCactpotSolver
PalacePal
PandorasBox
PennyPincher
PriceCheck
PriceInsight
Prioritizer
Questionable
RotationSolver
Saucy
SkipCutscene
utscene
Splatoon
TextAdvance
UnloadErrorFuckOff
vnavmesh
WhoDidThat
YesAlready

### Plugin config file

{
  "$type": "AutoDuty.Windows.Configuration, AutoDuty",
  "DoNotUpdatePathFiles": [],
  "PathSelections": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.Dictionary`2[[ECommons.ExcelServices.Job, ECommons],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib",
    "952": {
      "$type": "System.Collections.Generic.Dictionary`2[[ECommons.ExcelServices.Job, ECommons],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib",
      "MCH": 1,
      "RDM": 0
    },
    "1193": {
      "$type": "System.Collections.Generic.Dictionary`2[[ECommons.ExcelServices.Job, ECommons],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib"
    }
  },
  "AutoScroll": true,
  "LogEventLevel": 1,
  "LoopTimes": 100,
  "Unsynced": false,
  "HideUnavailableDuties": true,
  "ShowMainWindowOnStartup": false,
  "ShowDutyLoopText": true,
  "ShowActionText": true,
  "UseSliderInputs": false,
  "OverrideOverlayButtons": true,
  "GotoButton": true,
  "TurninButton": true,
  "DesynthButton": true,
  "ExtractButton": true,
  "RepairButton": true,
  "EquipButton": true,
  "AutoExitDuty": true,
  "AutoManageRotationPluginState": true,
  "AutoManageVnavAlignCamera": true,
  "LootTreasure": true,
  "LootMethodEnum": 0,
  "LootBossTreasureOnly": false,
  "TreasureCofferScanDistance": 25,
  "OverridePartyValidation": false,
  "UsingAlternativeRotationPlugin": false,
  "UsingAlternativeMovementPlugin": false,
  "UsingAlternativeBossPlugin": false,
  "EnablePreLoopActions": true,
  "ExecuteCommandsPreLoop": false,
  "CustomCommandsPreLoop": [],
  "RetireMode": false,
  "RetireLocationEnum": 0,
  "PersonalHomeEntrancePath": [],
  "FCEstateEntrancePath": [],
  "AutoEquipRecommendedGear": false,
  "AutoEquipRecommendedGearGearsetter": false,
  "AutoRepair": false,
  "AutoRepairPct": 50,
  "AutoRepairSelf": false,
  "PreferredRepairNPC": null,
  "AutoConsume": false,
  "AutoConsumeIgnoreStatus": false,
  "AutoConsumeItemsList": [],
  "EnableBetweenLoopActions": true,
  "WaitTimeBeforeAfterLoopActions": 0,
  "AutoExtract": false,
  "AutoGCTurninSlotsLeft": 5,
  "AutoGCTurninSlotsLeftBool": false,
  "AutoGCTurninUseTicket": false,
  "EnableAutoRetainer": false,
  "PreferredSummoningBellEnum": 0,
  "AM": false,
  "UnhideAM": false,
  "EnableTerminationActions": true,
  "StopLevel": false,
  "StopLevelInt": 1,
  "StopNoRestedXP": false,
  "StopItemQty": false,
  "StopItemQtyItemDictionary": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "StopItemQtyInt": 1,
  "ExecuteCommandsTermination": false,
  "CustomCommandsTermination": [],
  "PlayEndSound": false,
  "CustomSound": false,
  "CustomSoundVolume": 0.5,
  "SoundEnum": 0,
  "SoundPath": "",
  "TerminationMethodEnum": 0,
  "TerminationKeepActive": true,
  "HideBossModAIConfig": false,
  "FollowDuringCombat": true,
  "FollowDuringActiveBossModule": true,
  "FollowOutOfCombat": false,
  "FollowTarget": true,
  "FollowSlotInt": 1,
  "FollowRoleEnum": 1,
  "MaxDistanceToTargetFloat": 10.0,
  "MaxDistanceToTargetAoEFloat": 10.0,
  "MaxDistanceToSlotFloat": 1.0,
  "PositionalEnum": 0,
  "SelectedTrustMembers": [
    12,
    1,
    3
  ],
  "Version": 172,
  "DutyModeEnum": 2,
  "ShowOverlay": false,
  "HideOverlayWhenStopped": false,
  "LockOverlay": false,
  "OverlayNoBG": false,
  "AutoManageBossModAISettings": true,
  "AutoExtractAll": false,
  "AutoDesynth": false,
  "AutoDesynthSkillUp": false,
  "AutoGCTurnin": false,
  "FollowSelf": true,
  "FollowSlot": false,
  "FollowRole": false,
  "MaxDistanceToTargetRoleBased": true,
  "PositionalRoleBased": true
}

**Comment by erdelf** [comment]
this is more an issue of whatever combat plugin you are using.. I have no idea what the original Rotation Solver has for options.. but in RSR the proper option is near always small HP.

**Comment by Luysita** [comment]
> this is more an issue of whatever combat plugin you are using.. I have no idea what the original Rotation Solver has for options.. but in RSR the proper option is near always small HP.

That worked many thanks!

I followed the AutoDuty guide that says "tweaking the following options to use MaxHP rather than the defaults seems to do the trick." but I guess I'll test things out.
