### ISSUE TITLE
[Requests] Purchase Ventures after Expert Delivery / Next Dungeon based on level / Extract Materia

### ISSUE THREAD

**Issue by Dubsys** [ffxivcode/AutoDuty#64]
Hey, these features would be very handy for Autoduty,
1. handing in non armoury chest items for seals and then trading them for ventures.
2. being able to switch dungeons automatically based on level
i.e I set all items to go to my armoury chest, i hit the level threshhold, autoduty will equip recommended and then move to the next duty in the list.
3. Check extract status between dungeons and extract materia if possible

**Comment by adambennett55** [comment]
#1 is implemented with the use of Deliveroo Plugin
#2 will add to timeline
#3 same

**Comment by adambennett55** [comment]
3 has been added in v65

**Comment by rsigim** [comment]
For the 2 is possible to make a batch list? Because instead of just do N times a single dungeon leveling, we set to do a dungeon 5-6 times then to the next one, like the amount we would do anyway

**Comment by adambennett55** [comment]
2 - I believe there are a few forks working on this ATM, will update when PR's come in!!
