### ISSUE TITLE
[Feature Request] Cant install autoduty in dalamud

### ISSUE THREAD

**Issue by sssyaDavid** [ffxivcode/AutoDuty#659]
### What problem are you trying to fix?

Cannot install autoduty in dalamud

### What is the solution to the problem?

Dont know

**Comment by erdelf** [comment]
ok.. that's not a feature request for one.
What is your issue exactly, why can't you install it ?

**Comment by sssyaDavid** [comment]
I play Final Fantasy XIV on the Chinese server, and when I try to install autoduty in Dalamud, the AutoDuty plugin shows the error "The plugin failed to load." I have attempted multiple restarts and reinstalled it several times, but the issue persists. Could it be due to a version mismatch or something?

**Comment by erdelf** [comment]
CN is a patch and dalamud api version behind us.. so you would need to find the older versions in the releases .173 is the last for API 10

**Comment by sssyaDavid** [comment]
I think the CN server is using 7.05. I would like to know which version of autoduty I should download?  But I thought in dalamud they automatically change into the appropriate version?

**Comment by erdelf** [comment]
Dalamud does not do that. NA, JP, EU are on 7.1.
Best version you can get is 0.0.0.173.

**Comment by reenakaori** [comment]
Thank you for your explanation. Could you please tell me where I can find the version 0.0.0.173 plugin? I accidentally updated it to the latest version.

**Comment by Blexymoon** [comment]
I also have this problem,and this is Dalamud logs.I hope it help.

> 04:44:03.221 | ERR | [LOCALPLUGIN] Could not load one or more types when searching for IDalamudPlugin: C:\Users\90356\AppData\Roaming\XIVLauncherCN\installedPlugins\AutoDuty\0.0.0.178\AutoDuty.dll
	System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
	Could not load type 'Lumina.Excel.Sheets.ContentFinderCondition' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	Could not load type 'Lumina.Excel.Sheets.Aetheryte' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	Could not load type 'Lumina.Excel.Sheets.Aetheryte' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	Could not load type 'Lumina.Excel.Sheets.Aetheryte' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	Could not load type 'Lumina.Excel.Sheets.ENpcResident' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	Could not load type 'Lumina.Excel.Sheets.ClassJob' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
	   at System.Reflection.Assembly.GetTypes()
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.EnsureLoader()
	System.TypeLoadException: Could not load type 'Lumina.Excel.Sheets.ContentFinderCondition' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	System.TypeLoadException: Could not load type 'Lumina.Excel.Sheets.Aetheryte' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	System.TypeLoadException: Could not load type 'Lumina.Excel.Sheets.Aetheryte' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	System.TypeLoadException: Could not load type 'Lumina.Excel.Sheets.Aetheryte' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	System.TypeLoadException: Could not load type 'Lumina.Excel.Sheets.ENpcResident' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
	System.TypeLoadException: Could not load type 'Lumina.Excel.Sheets.ClassJob' from assembly 'Lumina.Excel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'.
04:44:03.246 | ERR | [LOCALPLUGIN] Error while loading "AutoDuty", failed to bind and call the plugin constructor
	System.AggregateException: Failed to create AutoDuty.AutoDuty (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.NullReferenceException: Object reference not set to an instance of an object.
	   at AutoDuty.AutoDuty..ctor() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 288
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, Boolean wrapInTargetInvocationException)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, Boolean wrapInTargetInvocationException)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0()
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope)
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope)
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass75_0.<<CreatePluginInstance>g__Create|0>d.MoveNext()
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.CreatePluginInstance(LocalPluginManifest manifest, IServiceScope scope, Type type, DalamudPluginInterface dalamudInterface)
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading)

**Comment by erdelf** [comment]
I can only assume you are also on CN? Again.. you'll have to load AD 173 until CN updates..

**Comment by seveninjur** [comment]
Hello.  Can you tell me can find the version  0.0.0.173.
