### ISSUE TITLE
[Bug] Bardam's Mettle issues

### ISSUE THREAD

**Issue by Faust-XIV** [ffxivcode/AutoDuty#673]
### What happened?

![image](https://github.com/user-attachments/assets/0f70e357-e518-4b04-9679-3b2094944dd5)

Having the tether is sure death and just kept on failing the 2nd boss trial.
Used both paths (1143) Bardam's Mettle and [Other W2W...]

### Version Number

v0.0.0178

### Steps to reproduce the error

1st boss: Not stretching tether which leads to death
2nd boss: Forever stuck on 1st trial.
>Golem will cast gaze and show first aoe marker.
>Character moves back to avoid
>2nd aoe marker appears
>Character just moves all the way back to the wall, getting hit by both aoe and gaze, failing the run and stuck in a loop.

### Other relevant plugins installed

BMR
vnavmesh

**Comment by erdelf** [comment]
that's the bmr module doing that.. not AD.
