### ISSUE TITLE
[Bug] AD Support Levelling mode not allowing selection

### ISSUE THREAD

**Issue by AWhite-Code** [ffxivcode/AutoDuty#705]
### What happened?

When selecting the Levelling Mode of auto support Support, I should be able to change from None to Auto. However it does not do this and simply stays as "None"

This is strange as it had been functioning fine the other day - I am unsure if I was playing on a previous version.

### Version Number

0.0.0.180

### Steps to reproduce the error

Open Auto Duty
Go to Main tab
Type in Number of Iterations
Select Support
Select "Auto"
Error occurs.

Can confirm the other modes still work, it is only the support function that seems to be having issues.

Fixes attempted - Please note this was done with all other plugins disabled except for Navmesh, boss mod, rotation solver and autoduty reborn.

Restarting Game
Disabling and Reenabling Plugin
Disabling and Deleting plugin
Disabling and Deleting plugin, then restarted game.

After each attempt I then tried to select 'auto' mode and the error occured.

### Relevant log output

```shell
Log is entirely empty.
```

### Other relevant plugins installed

Rotation Solver Reborn V7.1.1.15
Boss Mod Reborn V7.2.0.228
Vnavmesh V0.0.0.47

### Plugin config file

[AutoDuty.json](https://github.com/user-attachments/files/18137435/AutoDuty.json)

**Comment by erdelf** [comment]
in what world is your log entirely empty.. 
either way..
It switches back immediately if it can't find anything useful for you to do.
Usually means lvl is 100 or below 15.

**Comment by AWhite-Code** [comment]
Brother, I wish I could tell you, but I promise you, it was empty.

Regardless, I was an idiot last night - I was trying it on a level 100 class. 

Thanks for the swift response and the work you do for us goofy idiots. Have a good one, closing.
