### ISSUE TITLE
[Bug] Support Leveling, player healer doesn't heal NPCs and repeatedly wipes, RSR option not set

### ISSUE THREAD

**Issue by alyssadev** [ffxivcode/AutoDuty#706]
### What happened?

Leveling WHM, doing Brayflox, RSR doesn't do any healing for the NPCs and the party repeatedly wipes after the Scion Marauder dies. On opening RSR settings and enabling "Heal and raise Party NPCs. (Breaks some fights due to status weirdness)", AutoDuty can then run normally and finishes the dungeon.

### Version Number

v0.0.0.180

### Steps to reproduce the error

Low level WHM, duty support, Brayflox Longstop, wipes before first boss if "Heal and raise Party NPCs. (Breaks some fights due to status weirdness)" is not enabled in RSR

**Comment by erdelf** [comment]
Yes.. You do need to enable that in RSR correct.

**Comment by alyssadev** [comment]
Can AutoDuty set that option automatically?

**Comment by erdelf** [comment]
nope, it's not exposed. There is an AutoDuty section in RSR to help you.
