### ISSUE TITLE
Choosing companions in trust dungeons

### ISSUE THREAD

**Issue by ArmoredPuma** [ffxivcode/AutoDuty#71]
Hey! I love the plugon. I was just curious on if there is a way to choose the characters you take with you on the trust dungeons? I could very well be missing something but help would be super appreciated! Thanks again for your very valuable tool! :)

**Comment by adambennett55** [comment]
According to users on Discord, you can open the trust window, select your dungeon, select your trust members and enter the dungeon manually, then on the main tab select your number of loops and hist start and it should save those members for all subsequent runs.
