### ISSUE TITLE
[Bug] Path editor: modifying a step adds a duplicate step

### ISSUE THREAD

**Issue by Flavescent** [ffxivcode/AutoDuty#711]
### What happened?

When editing an action in the path editor, after the change is made, a duplicate of the modified action is added at the end of the patth.

### Version Number

0.0.0.180

### Steps to reproduce the error

Load into a dungeon that has a path. Double-click any action to modify it and confirm the change.

### Relevant log output

```shell
No log output
```

### Other relevant plugins installed

Some 90+plugins, no idea which might be relevant

**Comment by erdelf** [comment]
fixed in https://github.com/ffxivcode/AutoDuty/pull/717
