### ISSUE TITLE
[Bug] Auto Equip Doesn't work.

### ISSUE THREAD

**Issue by Battler624** [ffxivcode/AutoDuty#713]
### What happened?

https://i.imgur.com/cwzXymG.png

Gearsetter using the "/gup" commend shows that in my inventory (not armory chest) that I have 3 items I can use, the head, legs, & feet.
Pressing the "Equip" button in autoduty immediately saves the gearset (twice!) without changing the gear at all.
In the console it shows that it tried to correctly equip it but things are too fast I guess? I have no idea.

all autoduty settings https://i.imgur.com/ok1CDvH.png

### Version Number

.180

### Steps to reproduce the error

Have gear upgrade in inventory
press equip button.
watch.

**Comment by erdelf** [comment]
You say you read the log and see relevant output and then write there is no relevant output..?

**Comment by Battler624** [comment]
> You say you read the log and see relevant output and then write there is no relevant output..?

It's in the imgur url link
A picture of the console

**Comment by bUrself1** [comment]
Don't have a log output to contribute but, updating Gearsetter to v2.2 is when the problem started happening for me and downgrading to v2.1 fixed the issue.

**Comment by Battler624** [comment]
Could be the reason as I have only just started using anything really, I installed autoduty and gearsetter both yesterday.

**Comment by erdelf** [comment]
fixed in Gearsetter 2.3
