### ISSUE TITLE
Summoning pets after dying

### ISSUE THREAD

**Issue by UhRora** [ffxivcode/AutoDuty#72]
Hi, I was wondering if its possible to make it so we can summon our carbuncle/fairy after dying? I was running the level 93 dungeon and one of the NPCs killed me (sad face) and when we restarted, my character instantly started running. I have another plugin that automatically summons my pet but since its a cast, my character interrupts it by immediately sprinting to the shortcut. I figured out how to add a 'wait' action for the beginning of the dungeon so my character can cast, but after dying and respawning, I am unable to re-summon. I hope this makes sense

**Comment by adambennett55** [comment]
This really should be a RSR thing, Apparently, Pandora will do this for you as well, I can however implement into AutoDuty to stop or do not start movement when casting, when out of combat. it already does this when in combat.

**Comment by UhRora** [comment]
Will that fix it for just starting the dungeon or for dying while in a boss fight? Because every time I died, my character didnt even bother to start trying to cast 'summon carbuncle'. It immediately went straight for the shortcut to get back to the boss. I feel like maybe adding a wait action right after resurrecting so that the character can cast would be good.

**Comment by adambennett55** [comment]
This has been added in v66
