### ISSUE TITLE
[Feature Request] Configuration option for "Esc closes window" so I can turn it off and stop accidentally closing the overlay

### ISSUE THREAD

**Issue by thisischrys** [ffxivcode/AutoDuty#723]
### What problem are you trying to fix?

I often accidentally close the overlay if it's the last thing I clicked and then hit esc some time later meaning to close something else.

### What is the solution to the problem?

A configuration option for "Esc closes window" so I can turn it off.
Or just don't let esc close overlay? Makes more sense for the config window but not the overlay.

**Comment by erdelf** [comment]
fixed in https://github.com/ffxivcode/AutoDuty/pull/724
