### ISSUE TITLE
Melee range issue

### ISSUE THREAD

**Issue by Wilsonsreign** [ffxivcode/AutoDuty#95]
When melee characters move out of range during fights to avoid a mechanic it doesn’t move back into melee range after the mechanic is avoided. It makes the character stand in the same spot and use its ranged ability. I’d the target is out of range of ranged attacks the character idles until the enemy moves back into range or the character has to avoid another mechanic.

**Comment by erdelf** [comment]
Boss Mod Reborn has explicit settings to set the preferred range for exactly that.

**Comment by Wilsonsreign** [comment]
> Boss Mod Reborn has explicit settings to set the preferred range for exactly that.

I’m pretty new to mods overall. I didn’t know that. I appreciate the quick response.
